<?php
date_default_timezone_get('America/Bogota');

use App\Models\Para_Despacho;
use Illuminate\Database\Seeder;

class SeedParaDespacho extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 1, 'codigo' => '73L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 2, 'codigo' => '77L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 3, 'codigo' => '425L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 4, 'codigo' => '509L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 5, 'codigo' => '171S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 6, 'codigo' => '22S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 7, 'codigo' => '386S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 8, 'codigo' => '106S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 9, 'codigo' => '89S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 10, 'codigo' => '396S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 11, 'codigo' => '129S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 12, 'codigo' => '384L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 13, 'codigo' => '58S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 14, 'codigo' => '65S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 15, 'codigo' => '86S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 16, 'codigo' => '76S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 17, 'codigo' => '149S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 18, 'codigo' => '401L', 'nombre' => 'CENTRO DE ATENCIÓN PENAL INTEGRAL A VICTIMAS CAPIV'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 19, 'codigo' => '403L', 'nombre' => 'CENTRO DE ATENCIÓN PENAL INTEGRAL A VICTIMAS CAPIV'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 20, 'codigo' => '404L', 'nombre' => 'CENTRO DE ATENCIÓN PENAL INTEGRAL A VICTIMAS CAPIV'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 21, 'codigo' => '405L', 'nombre' => 'CENTRO DE ATENCIÓN PENAL INTEGRAL A VICTIMAS CAPIV'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 22, 'codigo' => '406L', 'nombre' => 'CENTRO DE ATENCIÓN PENAL INTEGRAL A VICTIMAS CAPIV'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 23, 'codigo' => '4', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 24, 'codigo' => '21', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 25, 'codigo' => '36', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 26, 'codigo' => '37', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 27, 'codigo' => '6', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 28, 'codigo' => '12', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 29, 'codigo' => '22', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 30, 'codigo' => '28', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 31, 'codigo' => '37 LEY 600', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 32, 'codigo' => '2', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 33, 'codigo' => '18', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 34, 'codigo' => '24', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 35, 'codigo' => '30', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 36, 'codigo' => '33', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 37, 'codigo' => '5', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 38, 'codigo' => '8', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 39, 'codigo' => '11', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 40, 'codigo' => '13', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 41, 'codigo' => '14', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 42, 'codigo' => '1', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 43, 'codigo' => '10', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 44, 'codigo' => '17', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 45, 'codigo' => '39', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 46, 'codigo' => '9', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 47, 'codigo' => '29', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 48, 'codigo' => '31', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 49, 'codigo' => '34', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 50, 'codigo' => '3', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 51, 'codigo' => '20', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 52, 'codigo' => '23', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 53, 'codigo' => '32', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 54, 'codigo' => '38', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 55, 'codigo' => '7', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 56, 'codigo' => '15', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 57, 'codigo' => '16', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 58, 'codigo' => '35', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 59, 'codigo' => '19', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 60, 'codigo' => '25', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 61, 'codigo' => '26', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 62, 'codigo' => '27', 'nombre' => 'JUZGADOS PENALES MUNICIPALES CON FUNCION DE CONOCIMIENTO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 63, 'codigo' => '8L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 64, 'codigo' => '157L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 65, 'codigo' => '35L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 66, 'codigo' => '279L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 67, 'codigo' => '36L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 68, 'codigo' => '280L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 69, 'codigo' => '66L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 70, 'codigo' => '293L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 71, 'codigo' => '99L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 72, 'codigo' => '296L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 73, 'codigo' => '379L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 74, 'codigo' => '355L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 75, 'codigo' => '380L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 76, 'codigo' => '361L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 77, 'codigo' => '385L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 78, 'codigo' => '365L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 79, 'codigo' => '387L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 80, 'codigo' => '376L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 81, 'codigo' => '424L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 82, 'codigo' => '147L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 83, 'codigo' => '353L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 84, 'codigo' => '205L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 85, 'codigo' => '364L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 86, 'codigo' => '277L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 87, 'codigo' => '367L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 88, 'codigo' => '298L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 89, 'codigo' => '381L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 90, 'codigo' => '334L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 91, 'codigo' => '13', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 92, 'codigo' => '53', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 93, 'codigo' => '28', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 94, 'codigo' => '55', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 95, 'codigo' => '33', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 96, 'codigo' => '56', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 97, 'codigo' => '44', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 98, 'codigo' => '61', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 99, 'codigo' => '48', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 100, 'codigo' => '64', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 101, 'codigo' => '50', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 102, 'codigo' => '67', 'nombre' => 'JUZGADOS DE GARANTIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 103, 'codigo' => '2L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 104, 'codigo' => '17L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 105, 'codigo' => '4L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 106, 'codigo' => '22L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 107, 'codigo' => '10L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 108, 'codigo' => '11L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 109, 'codigo' => '15L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 110, 'codigo' => '20L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 111, 'codigo' => '23L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 112, 'codigo' => '27L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 113, 'codigo' => '63L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 114, 'codigo' => '38L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 115, 'codigo' => '40L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 116, 'codigo' => '47L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 117, 'codigo' => '33L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 118, 'codigo' => '55L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 119, 'codigo' => '64L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 120, 'codigo' => '97L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 121, 'codigo' => '75L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 122, 'codigo' => '100L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 123, 'codigo' => '80L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 124, 'codigo' => '81L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 125, 'codigo' => '87L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 126, 'codigo' => '101L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 127, 'codigo' => '118L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 128, 'codigo' => '103L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 129, 'codigo' => '105L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 130, 'codigo' => '108L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 131, 'codigo' => '110L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 132, 'codigo' => '98L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 133, 'codigo' => '104L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 134, 'codigo' => '122L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 135, 'codigo' => '135L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 136, 'codigo' => '119L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 137, 'codigo' => '134L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 138, 'codigo' => '127L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 139, 'codigo' => '128L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 140, 'codigo' => '130L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 141, 'codigo' => '131L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 142, 'codigo' => '138L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 143, 'codigo' => '144L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 144, 'codigo' => '145L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 145, 'codigo' => '149L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 146, 'codigo' => '163L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 147, 'codigo' => '166L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 148, 'codigo' => '150L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 149, 'codigo' => '158L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 150, 'codigo' => '217L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 151, 'codigo' => '221L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 152, 'codigo' => '180L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 153, 'codigo' => '186L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 154, 'codigo' => '218L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 155, 'codigo' => '231L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 156, 'codigo' => '236L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 157, 'codigo' => '243L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 158, 'codigo' => '247L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 159, 'codigo' => '257L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 160, 'codigo' => '248L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 161, 'codigo' => '258L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 162, 'codigo' => '289L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 163, 'codigo' => '31L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 164, 'codigo' => '266L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 165, 'codigo' => '391L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 166, 'codigo' => '275L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 167, 'codigo' => '288L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 168, 'codigo' => '335L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 169, 'codigo' => '294L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 170, 'codigo' => '392L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 171, 'codigo' => '256L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 172, 'codigo' => '324L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 173, 'codigo' => '286L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 174, 'codigo' => '309L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 175, 'codigo' => '423L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 176, 'codigo' => '26L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 177, 'codigo' => '28L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 178, 'codigo' => '230L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 179, 'codigo' => '265L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 180, 'codigo' => '308L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 181, 'codigo' => '339L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 182, 'codigo' => '91L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 183, 'codigo' => '85L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 184, 'codigo' => '13L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 185, 'codigo' => '414L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 186, 'codigo' => '181L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 187, 'codigo' => '238L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 188, 'codigo' => '306L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 189, 'codigo' => '62L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 190, 'codigo' => '241L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 191, 'codigo' => '242L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 192, 'codigo' => '14L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 193, 'codigo' => '1L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 194, 'codigo' => '282L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 195, 'codigo' => '24L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 196, 'codigo' => '292L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 197, 'codigo' => '6L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 198, 'codigo' => '129L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 199, 'codigo' => '56L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 200, 'codigo' => '316L', 'nombre' => 'GRUPO DE CASOS QUERELLABLES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 201, 'codigo' => '291L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 202, 'codigo' => '115L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 203, 'codigo' => '370L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 204, 'codigo' => '386L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 205, 'codigo' => '502L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 206, 'codigo' => '398L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 1, 'valor' => 207, 'codigo' => '57L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 209, 'codigo' => '174S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 210, 'codigo' => '9S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 211, 'codigo' => '23S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 212, 'codigo' => '33S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 213, 'codigo' => '52S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 214, 'codigo' => '58L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 215, 'codigo' => '228S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 216, 'codigo' => '371L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 217, 'codigo' => '43S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 218, 'codigo' => '72S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 219, 'codigo' => '298S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 220, 'codigo' => '326L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 221, 'codigo' => '373L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 222, 'codigo' => '374L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 223, 'codigo' => '416L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 224, 'codigo' => '81S', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 225, 'codigo' => '372L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 226, 'codigo' => '415L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 227, 'codigo' => '417L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 228, 'codigo' => '418L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 229, 'codigo' => '419L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 230, 'codigo' => '510L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 231, 'codigo' => '60S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 232, 'codigo' => '63S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 233, 'codigo' => '68S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 234, 'codigo' => '133L', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 235, 'codigo' => '175L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 236, 'codigo' => '368L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 237, 'codigo' => '383S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 238, 'codigo' => '503L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 239, 'codigo' => '69L', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 240, 'codigo' => '50S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 241, 'codigo' => '142S', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 242, 'codigo' => '375S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 243, 'codigo' => '390S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 244, 'codigo' => '507L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 245, 'codigo' => '28S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 246, 'codigo' => '32S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 247, 'codigo' => '44S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 248, 'codigo' => '71S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 249, 'codigo' => '128S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 250, 'codigo' => '186S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 251, 'codigo' => '192S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 252, 'codigo' => '211S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 253, 'codigo' => '214S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 254, 'codigo' => '216S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 255, 'codigo' => '264S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 256, 'codigo' => '376S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 257, 'codigo' => '377S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 258, 'codigo' => '379S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA, CONTRA LA EFICAS Y RECTA IMPARTICIÓN DE JUSTICIA Y CONTRA LOS MECANISMOS DE PARTICIPACIÓN DEMOCRATICA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 259, 'codigo' => '45S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 260, 'codigo' => '236S', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 261, 'codigo' => '245S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 262, 'codigo' => '360L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 263, 'codigo' => '99S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 264, 'codigo' => '239S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 265, 'codigo' => '35S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 266, 'codigo' => '209S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 267, 'codigo' => '330S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 268, 'codigo' => '373S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 269, 'codigo' => '31S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 270, 'codigo' => '66S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 271, 'codigo' => '84S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 272, 'codigo' => '117S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 273, 'codigo' => '179S', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 274, 'codigo' => '187S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 275, 'codigo' => '205S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 276, 'codigo' => '244S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 277, 'codigo' => '248S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 278, 'codigo' => '250S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 279, 'codigo' => '254S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 280, 'codigo' => '256S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 281, 'codigo' => '257S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 282, 'codigo' => '258S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 283, 'codigo' => '262S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 284, 'codigo' => '266S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 285, 'codigo' => '271S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 286, 'codigo' => '273S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 287, 'codigo' => '301S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 288, 'codigo' => '340S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 289, 'codigo' => '358S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 290, 'codigo' => '378S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 291, 'codigo' => '384S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 292, 'codigo' => '501L', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 293, 'codigo' => '38S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 294, 'codigo' => '73S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 295, 'codigo' => '94S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 296, 'codigo' => '113L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 297, 'codigo' => '166S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 298, 'codigo' => '170L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 299, 'codigo' => '175S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 300, 'codigo' => '206S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 301, 'codigo' => '226S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 302, 'codigo' => '420L', 'nombre' => 'CENTRO DE ATENCIÓN PENAL INTEGRAL A VICTIMAS CAPIV'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 303, 'codigo' => '7S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 304, 'codigo' => '225S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 305, 'codigo' => '227S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 306, 'codigo' => '234S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 307, 'codigo' => '269S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 308, 'codigo' => '289S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 309, 'codigo' => '319S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 310, 'codigo' => '332S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 311, 'codigo' => '363S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 312, 'codigo' => '141S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 313, 'codigo' => '229S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 314, 'codigo' => '231S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 315, 'codigo' => '341S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 316, 'codigo' => '385S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 317, 'codigo' => '387S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 318, 'codigo' => '389S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 319, 'codigo' => '392S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 320, 'codigo' => '421L', 'nombre' => 'CENTRO DE ATENCIÓN PENAL INTEGRAL A VICTIMAS CAPIV'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 321, 'codigo' => '25S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 322, 'codigo' => '55S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 323, 'codigo' => '116L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 324, 'codigo' => '401S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 325, 'codigo' => '227L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 326, 'codigo' => '235L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 327, 'codigo' => '241S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 328, 'codigo' => '408L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 329, 'codigo' => '412L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 330, 'codigo' => '151S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 331, 'codigo' => '153S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 332, 'codigo' => '206L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 333, 'codigo' => '240S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 334, 'codigo' => '272L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 335, 'codigo' => '407L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 336, 'codigo' => '409L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 337, 'codigo' => '411L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 338, 'codigo' => '413L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 339, 'codigo' => '21L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 340, 'codigo' => '91S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 341, 'codigo' => '136S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 342, 'codigo' => '204S', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 343, 'codigo' => '239L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 344, 'codigo' => '262L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 345, 'codigo' => '410L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 346, 'codigo' => '152S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 347, 'codigo' => '107S', 'nombre' => 'LEY 600 DE 2000'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 348, 'codigo' => '39S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 349, 'codigo' => '120S', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 350, 'codigo' => '127S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 351, 'codigo' => '156S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 352, 'codigo' => '208S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 353, 'codigo' => '269L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 354, 'codigo' => '333S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 355, 'codigo' => '375L ', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 356, 'codigo' => '50L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 357, 'codigo' => '57S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 358, 'codigo' => '108S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 359, 'codigo' => '126S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 360, 'codigo' => '148S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 361, 'codigo' => '378L', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 362, 'codigo' => '19S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 363, 'codigo' => '49S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 364, 'codigo' => '69S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 365, 'codigo' => '85S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 366, 'codigo' => '88S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 367, 'codigo' => '102L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 368, 'codigo' => '105S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 369, 'codigo' => '111S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 370, 'codigo' => '140S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 371, 'codigo' => '144S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 372, 'codigo' => '160S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 373, 'codigo' => '170S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 374, 'codigo' => '61S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 375, 'codigo' => '79S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 376, 'codigo' => '93S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 377, 'codigo' => '75S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 378, 'codigo' => '181S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 379, 'codigo' => '115S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 380, 'codigo' => '118S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 381, 'codigo' => '124S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 382, 'codigo' => '139S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 383, 'codigo' => '134S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 384, 'codigo' => '147S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 385, 'codigo' => '169S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 386, 'codigo' => '150S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 387, 'codigo' => '162S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 388, 'codigo' => '98S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 389, 'codigo' => '101S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 390, 'codigo' => '159S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 391, 'codigo' => '172S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 392, 'codigo' => '242S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 393, 'codigo' => '336S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 394, 'codigo' => '157S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 395, 'codigo' => '184S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 396, 'codigo' => '221S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 397, 'codigo' => '104S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 398, 'codigo' => '309S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 399, 'codigo' => '362S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 400, 'codigo' => '388S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 401, 'codigo' => '393S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 402, 'codigo' => '238S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 403, 'codigo' => '243S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 404, 'codigo' => '277S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 405, 'codigo' => '287S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 406, 'codigo' => '328S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 407, 'codigo' => '366S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 408, 'codigo' => '381S', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 409, 'codigo' => '96L', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 410, 'codigo' => '143L', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 411, 'codigo' => '125L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 412, 'codigo' => '201L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 413, 'codigo' => '209L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 414, 'codigo' => '211L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 415, 'codigo' => '274L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 416, 'codigo' => '283S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 417, 'codigo' => '302S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 418, 'codigo' => '305S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 419, 'codigo' => '314S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 420, 'codigo' => '327L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 421, 'codigo' => '330L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 422, 'codigo' => '332L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 423, 'codigo' => '348S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 424, 'codigo' => '359S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 425, 'codigo' => '14S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 426, 'codigo' => '95L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 427, 'codigo' => '183L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 428, 'codigo' => '214L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 429, 'codigo' => '240L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 430, 'codigo' => '279S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 431, 'codigo' => '287L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 432, 'codigo' => '293S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 433, 'codigo' => '321S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 434, 'codigo' => '322S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 435, 'codigo' => '326S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 436, 'codigo' => '329L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 437, 'codigo' => '361S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 438, 'codigo' => '390L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 439, 'codigo' => '39L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 440, 'codigo' => '195L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 441, 'codigo' => '200L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 442, 'codigo' => '259L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 443, 'codigo' => '281L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 444, 'codigo' => '284S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 445, 'codigo' => '513L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 446, 'codigo' => '292S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 447, 'codigo' => '300S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 448, 'codigo' => '301L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 449, 'codigo' => '311S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 450, 'codigo' => '311L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 451, 'codigo' => '331L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 452, 'codigo' => '360S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 453, 'codigo' => '18S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 454, 'codigo' => '87S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 455, 'codigo' => '202L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 456, 'codigo' => '210S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 457, 'codigo' => '212L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 458, 'codigo' => '237S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 459, 'codigo' => '300L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 460, 'codigo' => '303L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 461, 'codigo' => '305L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 462, 'codigo' => '306S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 463, 'codigo' => '307L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 464, 'codigo' => '312L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 465, 'codigo' => '324S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 466, 'codigo' => '328L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 467, 'codigo' => '24S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 468, 'codigo' => '107L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 469, 'codigo' => '198L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 470, 'codigo' => '203L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 471, 'codigo' => '210L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 472, 'codigo' => '213L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 473, 'codigo' => '274S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 474, 'codigo' => '282S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 475, 'codigo' => '296S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 476, 'codigo' => '304L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 477, 'codigo' => '312S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 478, 'codigo' => '318L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 479, 'codigo' => '321L', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 480, 'codigo' => '323S', 'nombre' => 'UNIDAD DE REACCIÓN INMEDIATA'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 481, 'codigo' => '395S', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 482, 'codigo' => '291S', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 483, 'codigo' => '422L', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA SEGURIDAD PÚBLICA, SALUD PÚBLICA, LIBERTAD INDIVIDUAL Y OTROS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 484, 'codigo' => '508L', 'nombre' => 'UNIDAD CONTRA LA VIDA E INTEGRIDAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 485, 'codigo' => '99L', 'nombre' => 'UNIDAD DE GESTIÓN DE ALERTAS Y CLASIFICACIÓN TEMPRANA DE DENUNCIAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 486, 'codigo' => '132S', 'nombre' => 'UNIDAD DE ESTRUCTURA DE APOYO'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 487, 'codigo' => '7L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 488, 'codigo' => '37L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 489, 'codigo' => '68L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 490, 'codigo' => '76L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 491, 'codigo' => '88L', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 492, 'codigo' => '92L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 493, 'codigo' => '148L', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 494, 'codigo' => '174L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 495, 'codigo' => '179L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 496, 'codigo' => '197L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 497, 'codigo' => '223L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 498, 'codigo' => '263L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 499, 'codigo' => '224L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 500, 'codigo' => '229L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 501, 'codigo' => '369L', 'nombre' => 'UNIDAD DE HURTOS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 502, 'codigo' => '426L', 'nombre' => 'UNIDAD DE ESTAFAS'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 503, 'codigo' => '207L', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 504, 'codigo' => '167E', 'nombre' => 'DIRECCIÓN ESPECIALIZADA CONTRA EL CRIMEN ORGANIZADO DECOC'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 505, 'codigo' => '28E ', 'nombre' => 'GRUPO DE INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 506, 'codigo' => '152L', 'nombre' => 'UNIDAD DE HURTO '),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 507, 'codigo' => '397L', 'nombre' => '397L'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 508, 'codigo' => '260L', 'nombre' => 'INVESTIGACIÓN Y JUDICIALIZACIÓN'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 509, 'codigo' => '359L', 'nombre' => 'UNIDAD DE LIBERTAD PERSONAL'),
            array('usuario_crea' => 0, 'id_tipo_mp' => 2, 'valor' => 510, 'codigo' => '351S', 'nombre' => 'UNIDAD DE DELITOS CONTRA LA LIBERTAD, INTEGRIDAD Y FORMACIÓN SEXUALES'),            
        ];
        for ($i=0; $i < count($datos); $i++) { 
            Para_Despacho::create($datos[$i]);
        }
    }
}
