<?php
date_default_timezone_get('America/Bogota');

use App\Models\Para_Delito;
use Illuminate\Database\Seeder;

class SeedParaDelito extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            array('usuario_crea' => 0, 'valor' => 1, 'codigo' => '101', 'nombre' => 'GENOCIDIO'),
            array('usuario_crea' => 0, 'valor' => 2, 'codigo' => '102', 'nombre' => 'APOLOGÍA DEL GENOCIDIO'),
            array('usuario_crea' => 0, 'valor' => 3, 'codigo' => '103', 'nombre' => 'HOMICIDIO'),
            array('usuario_crea' => 0, 'valor' => 4, 'codigo' => '104 A', 'nombre' => 'FEMINICIDIO'),
            array('usuario_crea' => 0, 'valor' => 5, 'codigo' => '105', 'nombre' => 'HOMICIDIO PRETERINTENCIONAL'),
            array('usuario_crea' => 0, 'valor' => 6, 'codigo' => '106', 'nombre' => 'HOMICIDIO POR PIEDAD'),
            array('usuario_crea' => 0, 'valor' => 7, 'codigo' => '107', 'nombre' => 'INDUCCION O AYUDA AL SUICIDIO'),
            array('usuario_crea' => 0, 'valor' => 8, 'codigo' => '108', 'nombre' => 'MUERTE DE HIJO FRUTO DE ACCESO CARNAL VIOLENTO, ABUSIVO, O DE INSEMINACION ARTIFICIAL O TRANSFERENCIA DE OVULO FECUNDADO NO CONSENTIDAS'),
            array('usuario_crea' => 0, 'valor' => 9, 'codigo' => '109', 'nombre' => 'HOMICIDIO CULPOSO.'),
            array('usuario_crea' => 0, 'valor' => 10, 'codigo' => '111', 'nombre' => 'LESIONES.'),
            array('usuario_crea' => 0, 'valor' => 11, 'codigo' => '112', 'nombre' => 'INCAPACIDAD PARA TRABAJAR O ENFERMEDAD'),
            array('usuario_crea' => 0, 'valor' => 12, 'codigo' => '113', 'nombre' => 'DEFORMIDAD'),
            array('usuario_crea' => 0, 'valor' => 13, 'codigo' => '114', 'nombre' => 'PERTURBACIÓN FUNCIONAL'),
            array('usuario_crea' => 0, 'valor' => 14, 'codigo' => '115', 'nombre' => 'PERTURBACIÓN PSÍQUICA'),
            array('usuario_crea' => 0, 'valor' => 15, 'codigo' => '116', 'nombre' => 'PÉRDIDA ANATÓMICA O FUNCIONAL DE UN ORGANO O MIEMBRO'),
            array('usuario_crea' => 0, 'valor' => 16, 'codigo' => '116 A', 'nombre' => 'LESIONES CON AGENTES QUÍMICOS, ÁCIDO Y/O SUSTANCIAS SIMILARES'),
            array('usuario_crea' => 0, 'valor' => 17, 'codigo' => '117', 'nombre' => 'UNIDAD PUNITIVA'),
            array('usuario_crea' => 0, 'valor' => 18, 'codigo' => '118', 'nombre' => 'PARTO O ABORTO PRETERINTENCIONAL'),
            array('usuario_crea' => 0, 'valor' => 19, 'codigo' => '120', 'nombre' => 'LESIONES CULPOSAS'),
            array('usuario_crea' => 0, 'valor' => 20, 'codigo' => '122', 'nombre' => 'ABORTO'),
            array('usuario_crea' => 0, 'valor' => 21, 'codigo' => '123', 'nombre' => 'AORTO SIN CONSENTIMIENTO'),
            array('usuario_crea' => 0, 'valor' => 22, 'codigo' => '124', 'nombre' => 'INEXEQUIBLE'),
            array('usuario_crea' => 0, 'valor' => 23, 'codigo' => '125', 'nombre' => 'LESIONES AL FETO'),
            array('usuario_crea' => 0, 'valor' => 24, 'codigo' => '126', 'nombre' => 'LESIONES CULPOSAS AL FETO'),
            array('usuario_crea' => 0, 'valor' => 25, 'codigo' => '127', 'nombre' => 'ABANDONO'),
            array('usuario_crea' => 0, 'valor' => 26, 'codigo' => '128', 'nombre' => 'ABANDONO DE HIJO FRUTO DE ACCESO CARNAL VIOLENTO, ABUSIVO, O DE INSEMINACION ARTIFICIAL O TRANSFERENCIA DE OVULO FECUNDADO NO CONSENTIDAS'),
            array('usuario_crea' => 0, 'valor' => 27, 'codigo' => '130', 'nombre' => 'CIRCUSTANCIAS DE AGRVACIÓN'),
            array('usuario_crea' => 0, 'valor' => 28, 'codigo' => '131', 'nombre' => 'OMISION DE SOCORRO'),
            array('usuario_crea' => 0, 'valor' => 29, 'codigo' => '132', 'nombre' => 'MANIPULACION GENETICA.'),
            array('usuario_crea' => 0, 'valor' => 30, 'codigo' => '133', 'nombre' => 'REPETIBILIDAD DEL SER HUMANO'),
            array('usuario_crea' => 0, 'valor' => 31, 'codigo' => '134', 'nombre' => 'FECUNDACION Y TRAFICO DE EMBRIONES HUMANOS.'),
            array('usuario_crea' => 0, 'valor' => 32, 'codigo' => '134 A', 'nombre' => 'ACTOS DE DISCRIMINACIÓN.'),
            array('usuario_crea' => 0, 'valor' => 33, 'codigo' => '134 B', 'nombre' => 'HOSTIGAMIENTO'),
            array('usuario_crea' => 0, 'valor' => 34, 'codigo' => '135', 'nombre' => 'HOMICIDIO EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 35, 'codigo' => '136', 'nombre' => 'LESIONES EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 36, 'codigo' => '137', 'nombre' => 'TORTURA EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 37, 'codigo' => '138', 'nombre' => 'ACCESO CARNAL VIOLENTO EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 38, 'codigo' => '138 A', 'nombre' => 'ACCESO CARNAL ABUSIVO EN PERSONA PROTEGIDA MENOR DE CATORCE AÑOS'),
            array('usuario_crea' => 0, 'valor' => 39, 'codigo' => '139', 'nombre' => 'ACTOS SEXUALES VIOLENTOS EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 40, 'codigo' => '139 A', 'nombre' => 'ACTOS SEXUALES CON PERSONA PROTEGIDA MENOR DE CATORCE AÑOS'),
            array('usuario_crea' => 0, 'valor' => 41, 'codigo' => '139 B', 'nombre' => 'ESTERILIZACIÓN FORZADA EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 42, 'codigo' => '139 C', 'nombre' => 'EMBARAZO FORZADO EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 43, 'codigo' => '139 D', 'nombre' => 'DESNUDEZ FORZADA EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 44, 'codigo' => '139 E', 'nombre' => 'ABORTO FORZADO EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 45, 'codigo' => '140', 'nombre' => 'CIRCUSTANCIAS DE AGRABACIÓN'),
            array('usuario_crea' => 0, 'valor' => 46, 'codigo' => '141', 'nombre' => 'PROSTITUCIÓN FORZADA EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 47, 'codigo' => '141 A', 'nombre' => 'ESCLAVITUD SEXUAL EN PERSONA PROTEGIDA.'),
            array('usuario_crea' => 0, 'valor' => 48, 'codigo' => '141 B', 'nombre' => 'TRATA DE PERSONAS EN PERSONA PROTEGIDA CON FINES DE EXPLOTACIÓN SEXUAL'),
            array('usuario_crea' => 0, 'valor' => 49, 'codigo' => '142', 'nombre' => 'UTILIZACION DE MEDIOS Y METODOS DE GUERRA ILICITOS'),
            array('usuario_crea' => 0, 'valor' => 50, 'codigo' => '143', 'nombre' => 'PERFIDIA.'),
            array('usuario_crea' => 0, 'valor' => 51, 'codigo' => '144', 'nombre' => 'ACTOS DE TERRORISMO'),
            array('usuario_crea' => 0, 'valor' => 52, 'codigo' => '145', 'nombre' => 'ACTOS DE BARBARIE.'),
            array('usuario_crea' => 0, 'valor' => 53, 'codigo' => '146', 'nombre' => 'TRATOS INHUMANOS Y DEGRADANTES Y EXPERIMENTOS BIOLOGICOS EN PERSONA PROTEGIDA'),
            array('usuario_crea' => 0, 'valor' => 54, 'codigo' => '147', 'nombre' => 'ACTOS DE DISCRIMINACION RACIAL'),
            array('usuario_crea' => 0, 'valor' => 55, 'codigo' => '148', 'nombre' => 'TOMA DE REHENES'),
            array('usuario_crea' => 0, 'valor' => 56, 'codigo' => '149', 'nombre' => 'DETENCION ILEGAL Y PRIVACION DEL DEBIDO PROCESO'),
            array('usuario_crea' => 0, 'valor' => 57, 'codigo' => '150', 'nombre' => 'CONSTREÑIMIENTO A APOYO BELICO. '),
            array('usuario_crea' => 0, 'valor' => 58, 'codigo' => '151', 'nombre' => 'DESPOJO EN EL CAMPO DE BATALLA.'),
            array('usuario_crea' => 0, 'valor' => 59, 'codigo' => '152', 'nombre' => 'OMISION DE MEDIDAS DE SOCORRO Y ASISTENCIA HUMANITARIA.'),
            array('usuario_crea' => 0, 'valor' => 60, 'codigo' => '153', 'nombre' => 'OBSTACULIZACION DE TAREAS SANITARIAS Y HUMANITARIAS'),
            array('usuario_crea' => 0, 'valor' => 61, 'codigo' => '154', 'nombre' => 'DESTRUCCION Y APROPIACION DE BIENES PROTEGIDOS'),
            array('usuario_crea' => 0, 'valor' => 62, 'codigo' => '155', 'nombre' => 'DESTRUCCION DE BIENES E INSTALACIONES DE CARACTER SANITARIO'),
            array('usuario_crea' => 0, 'valor' => 63, 'codigo' => '156', 'nombre' => 'DESTRUCCION O UTILIZACION ILICITA DE BIENES CULTURALES Y DE LUGARES DE CULTO'),
            array('usuario_crea' => 0, 'valor' => 64, 'codigo' => '157', 'nombre' => 'ATAQUE CONTRA OBRAS E INSTALACIONES QUE CONTIENEN FUERZAS PELIGROSAS'),
            array('usuario_crea' => 0, 'valor' => 65, 'codigo' => '158', 'nombre' => 'ATAQUE CONTRA OBRAS E INSTALACIONES QUE CONTIENEN FUERZAS PELIGROSAS'),
            array('usuario_crea' => 0, 'valor' => 66, 'codigo' => '159', 'nombre' => 'DEPORTACION, EXPULSION, TRASLADO O DESPLAZAMIENTO FORZADO DE POBLACION CIVIL'),
            array('usuario_crea' => 0, 'valor' => 67, 'codigo' => '160', 'nombre' => 'ATENTADOS A LA SUBSISTENCIA Y DEVASTACION'),
            array('usuario_crea' => 0, 'valor' => 68, 'codigo' => '161', 'nombre' => 'OMISION DE MEDIDAS DE PROTECCION A LA POBLACION CIVIL'),
            array('usuario_crea' => 0, 'valor' => 69, 'codigo' => '162', 'nombre' => 'RECLUTAMIENTO ILICITO.'),
            array('usuario_crea' => 0, 'valor' => 70, 'codigo' => '163', 'nombre' => 'EXACCION O CONTRIBUCIONES ARBITRARIAS'),
            array('usuario_crea' => 0, 'valor' => 71, 'codigo' => '164', 'nombre' => 'DESTRUCCION DEL MEDIO AMBIENTE'),
            array('usuario_crea' => 0, 'valor' => 72, 'codigo' => '165', 'nombre' => 'DESAPARICION FORZADA'),
            array('usuario_crea' => 0, 'valor' => 73, 'codigo' => '168', 'nombre' => 'SECUESTRO SIMPLE.'),
            array('usuario_crea' => 0, 'valor' => 74, 'codigo' => '169', 'nombre' => 'SECUESTRO EXTORSIVO'),
            array('usuario_crea' => 0, 'valor' => 75, 'codigo' => '172', 'nombre' => 'DEROGADO'),
            array('usuario_crea' => 0, 'valor' => 76, 'codigo' => '173', 'nombre' => 'APODERAMIENTO DE AERONAVES, NAVES, O MEDIOS DE TRANSPORTE COLECTIVO.'),
            array('usuario_crea' => 0, 'valor' => 77, 'codigo' => '174', 'nombre' => 'PRIVACION ILEGAL DE LIBERTAD.'),
            array('usuario_crea' => 0, 'valor' => 78, 'codigo' => '175', 'nombre' => 'PROLONGACION ILICITA DE PRIVACION DE LA LIBERTAD'),
            array('usuario_crea' => 0, 'valor' => 79, 'codigo' => '176', 'nombre' => 'DETENCION ARBITRARIA ESPECIA'),
            array('usuario_crea' => 0, 'valor' => 80, 'codigo' => '177', 'nombre' => 'DESCONOCIMIENTO DE HÁBEAS CORPUS'),
            array('usuario_crea' => 0, 'valor' => 81, 'codigo' => '178', 'nombre' => 'TORTURA'),
            array('usuario_crea' => 0, 'valor' => 82, 'codigo' => '180', 'nombre' => 'DESPLAZAMIENTO FORZADO'),
            array('usuario_crea' => 0, 'valor' => 83, 'codigo' => '182', 'nombre' => 'CONSTREÑIMIENTO ILEGAL'),
            array('usuario_crea' => 0, 'valor' => 84, 'codigo' => '184', 'nombre' => 'CONSTREÑIMIENTO PARA DELINQUIR.'),
            array('usuario_crea' => 0, 'valor' => 85, 'codigo' => '186', 'nombre' => 'FRAUDULENTA INTERNACION EN ASILO, CLINICA O ESTABLECIMIENTO SIMILAR'),
            array('usuario_crea' => 0, 'valor' => 86, 'codigo' => '187', 'nombre' => 'INSEMINACION ARTIFICIAL O TRANSFERENCIA DE OVULO FECUNDADO NO CONSENTIDAS'),
            array('usuario_crea' => 0, 'valor' => 87, 'codigo' => '188', 'nombre' => 'DEL TRÁFICO DE MIGRANTES'),
            array('usuario_crea' => 0, 'valor' => 88, 'codigo' => '188 A', 'nombre' => 'TRATA DE PERSONAS'),
            array('usuario_crea' => 0, 'valor' => 89, 'codigo' => '188 C', 'nombre' => 'TRÁFICO DE NIÑAS, NIÑOS Y ADOLESCENTES'),
            array('usuario_crea' => 0, 'valor' => 90, 'codigo' => '188 D', 'nombre' => 'USO DE MENORES DE EDAD LA COMISIÓN DE DELITOS'),
            array('usuario_crea' => 0, 'valor' => 91, 'codigo' => '188 E', 'nombre' => 'AMENAZAS CONTRA DEFENSORES DE DERECHOS HUMANOS Y SERVIDORES PÚBLICOS'),
            array('usuario_crea' => 0, 'valor' => 92, 'codigo' => '189', 'nombre' => 'VIOLACIÓN DE HABITACIÓN AJENA'),
            array('usuario_crea' => 0, 'valor' => 93, 'codigo' => '190', 'nombre' => 'VIOLACION DE HABITACION AJENA POR SERVIDOR PUBLICO'),
            array('usuario_crea' => 0, 'valor' => 94, 'codigo' => '191', 'nombre' => 'VIOLACION EN LUGAR DE TRABAJO'),
            array('usuario_crea' => 0, 'valor' => 95, 'codigo' => '192', 'nombre' => 'VIOLACION ILICITA DE COMUNICACIONES'),
            array('usuario_crea' => 0, 'valor' => 96, 'codigo' => '193', 'nombre' => 'OFRECIMIENTO, VENTA O COMPRA DE INSTRUMENTO APTO PARA INTERCEPTAR LA COMUNICACION PRIVADA ENTRE PERSONAS'),
            array('usuario_crea' => 0, 'valor' => 97, 'codigo' => '194', 'nombre' => 'DIVULGACION Y EMPLEO DE DOCUMENTOS RESERVADOS'),
            array('usuario_crea' => 0, 'valor' => 98, 'codigo' => '195', 'nombre' => 'DEROGADO'),
            array('usuario_crea' => 0, 'valor' => 99, 'codigo' => '196', 'nombre' => 'VIOLACION ILICITA DE COMUNICACIONES O CORRESPONDENCIA DE CARACTER OFICIAL.'),
            array('usuario_crea' => 0, 'valor' => 100, 'codigo' => '197', 'nombre' => 'UTILIZACIÓN ILÍCITA DE REDES DE COMUNICACIONES'),
            array('usuario_crea' => 0, 'valor' => 101, 'codigo' => '198', 'nombre' => 'VIOLACION DE LA LIBERTAD DE TRABAJO'),
            array('usuario_crea' => 0, 'valor' => 102, 'codigo' => '199', 'nombre' => 'SABOTAJE. '),
            array('usuario_crea' => 0, 'valor' => 103, 'codigo' => '200', 'nombre' => 'VIOLACIÓN DE LOS DERECHOS DE REUNIÓN Y ASOCIACIÓN'),
            array('usuario_crea' => 0, 'valor' => 104, 'codigo' => '201', 'nombre' => 'VIOLACION A LA LIBERTAD RELIGIOSA'),
            array('usuario_crea' => 0, 'valor' => 105, 'codigo' => '202', 'nombre' => 'IMPEDIMENTO Y PERTURBACION DE CEREMONIA RELIGIOSA'),
            array('usuario_crea' => 0, 'valor' => 106, 'codigo' => '203', 'nombre' => 'DAÑOS O AGRAVIOS A PERSONAS O A COSAS DESTINADAS AL CULTO.'),
            array('usuario_crea' => 0, 'valor' => 107, 'codigo' => '204', 'nombre' => 'IRRESPETO A CADAVERES'),
            array('usuario_crea' => 0, 'valor' => 108, 'codigo' => '205', 'nombre' => 'ACCESO CARNAL VIOLENTO'),
            array('usuario_crea' => 0, 'valor' => 109, 'codigo' => '206', 'nombre' => 'ACTO SEXUAL VIOLENTO'),
            array('usuario_crea' => 0, 'valor' => 110, 'codigo' => '207', 'nombre' => 'ACCESO CARNAL O ACTO SEXUAL EN PERSONA PUESTA EN INCAPACIDAD DE RESISTIR. '),
            array('usuario_crea' => 0, 'valor' => 111, 'codigo' => '208', 'nombre' => 'ACCESO CARNAL ABUSIVO CON MENOR DE CATORCE AÑOS'),
            array('usuario_crea' => 0, 'valor' => 112, 'codigo' => '209', 'nombre' => 'ACTOS SEXUALES CON MENOR DE CATORCE AÑOS'),
            array('usuario_crea' => 0, 'valor' => 113, 'codigo' => '210', 'nombre' => 'ACCESO CARNAL O ACTO SEXUAL ABUSIVOS CON INCAPAZ DE RESISTIR.'),
            array('usuario_crea' => 0, 'valor' => 114, 'codigo' => '210 A', 'nombre' => 'ACOSO SEXUAL'),
            array('usuario_crea' => 0, 'valor' => 115, 'codigo' => '213', 'nombre' => 'INDUCCION A LA PROSTITUCION'),
            array('usuario_crea' => 0, 'valor' => 116, 'codigo' => '213 A', 'nombre' => 'PROXENETISMO CON MENOR DE EDAD'),
            array('usuario_crea' => 0, 'valor' => 117, 'codigo' => '214', 'nombre' => 'CONSTREÑIMIENTO A LA PROSTITUCIÓN'),
            array('usuario_crea' => 0, 'valor' => 118, 'codigo' => '215', 'nombre' => 'DEROGADO'),
            array('usuario_crea' => 0, 'valor' => 119, 'codigo' => '217', 'nombre' => 'ESTIMULO A LA PROSTITUCIÓN DE MENORES'),
            array('usuario_crea' => 0, 'valor' => 120, 'codigo' => '217A', 'nombre' => 'DEMANDA DE EXPLOTACIÓN SEXUAL COMERCIAL DE PERSONA MENOR DE 18 AÑOS DE EDAD'),
            array('usuario_crea' => 0, 'valor' => 121, 'codigo' => '218', 'nombre' => 'PORNOGRAFIA CON PERSONA MENOR DE 18 AÑOS DE EDAD'),
            array('usuario_crea' => 0, 'valor' => 122, 'codigo' => '219', 'nombre' => 'TURISMO SEXUAL'),
            array('usuario_crea' => 0, 'valor' => 123, 'codigo' => '219A', 'nombre' => 'UTILIZACIÓN O FACILITACIÓN DE MEDIOS DE COMUNICACIÓN PARA OFRECER ACTIVIDADES SEXUALES CON PERSONAS MENORES DE 18 AÑOS DE EDAD.'),
            array('usuario_crea' => 0, 'valor' => 124, 'codigo' => '219B', 'nombre' => 'OMISIÓN DE DENUNCIA'),
            array('usuario_crea' => 0, 'valor' => 125, 'codigo' => '219C', 'nombre' => 'INABILIDADES POR DELITOS SEXUALES COMETIDOS CONTRA MENORES.'),
            array('usuario_crea' => 0, 'valor' => 126, 'codigo' => '220', 'nombre' => 'INJURIA'),
            array('usuario_crea' => 0, 'valor' => 127, 'codigo' => '221', 'nombre' => 'CALUMNIA'),
            array('usuario_crea' => 0, 'valor' => 128, 'codigo' => '222', 'nombre' => 'INJURIA Y CALUMNIA INDIRECTAS'),
            array('usuario_crea' => 0, 'valor' => 129, 'codigo' => '223', 'nombre' => 'CIRCUNSTANCIAS ESPECIALES DE GRADUACIÓN DE LA PENA'),
            array('usuario_crea' => 0, 'valor' => 130, 'codigo' => '224', 'nombre' => '224'),
            array('usuario_crea' => 0, 'valor' => 131, 'codigo' => '225', 'nombre' => '225'),
            array('usuario_crea' => 0, 'valor' => 132, 'codigo' => '226', 'nombre' => 'INJURIAS POR VIAS DE HECHO'),
            array('usuario_crea' => 0, 'valor' => 133, 'codigo' => '227', 'nombre' => 'INJURIAS O CALUMNIAS RECIPROCAS'),
            array('usuario_crea' => 0, 'valor' => 134, 'codigo' => '228', 'nombre' => 'IMPUTACIONES DE LITIGANTES'),
            array('usuario_crea' => 0, 'valor' => 135, 'codigo' => '229', 'nombre' => 'VIOLENCIA INTRAFAMILIAR'),
            array('usuario_crea' => 0, 'valor' => 136, 'codigo' => '230', 'nombre' => 'MALTRATO MEDIANTE RESTRICCIÓN A LA LIUBERTAD FÍSICA'),
            array('usuario_crea' => 0, 'valor' => 137, 'codigo' => '230A', 'nombre' => 'EJERCICIO ARBITRARIO DE DE LA CUSTODIA DE HIJO MENOR DE EDAD'),
            array('usuario_crea' => 0, 'valor' => 138, 'codigo' => '231', 'nombre' => 'EXPLOTACIÓN DE MENORES DE EDAD'),
            array('usuario_crea' => 0, 'valor' => 139, 'codigo' => '232', 'nombre' => 'ADOPCIÓN IRREGULAR'),
            array('usuario_crea' => 0, 'valor' => 140, 'codigo' => '233', 'nombre' => 'INACISTENCIA ALIMENTARIA'),
            array('usuario_crea' => 0, 'valor' => 141, 'codigo' => '235', 'nombre' => 'REITERACIÓN'),
            array('usuario_crea' => 0, 'valor' => 142, 'codigo' => '236', 'nombre' => 'MALVERSACIÓN Y DILAPIDACIÓN DE BIENES FAMILIARES'),
            array('usuario_crea' => 0, 'valor' => 143, 'codigo' => '237', 'nombre' => 'INCESTO'),
            array('usuario_crea' => 0, 'valor' => 144, 'codigo' => '238', 'nombre' => 'SUPRESIÓN, ALTERACIÓN O SUPOSICIÓN DEL ESTADO CIVIL'),
            array('usuario_crea' => 0, 'valor' => 145, 'codigo' => '239', 'nombre' => 'HURTO'),
            array('usuario_crea' => 0, 'valor' => 146, 'codigo' => '240', 'nombre' => 'HURTO CALIFICADO'),
            array('usuario_crea' => 0, 'valor' => 147, 'codigo' => '243', 'nombre' => 'ABIGEATO'),
            array('usuario_crea' => 0, 'valor' => 148, 'codigo' => '244', 'nombre' => 'EXTORSIÓN'),
            array('usuario_crea' => 0, 'valor' => 149, 'codigo' => '246', 'nombre' => 'ESTAFA'),
            array('usuario_crea' => 0, 'valor' => 150, 'codigo' => '248', 'nombre' => 'EMISION Y TRANSFERENCIA ILEGAL DE CHEQUE.'),
            array('usuario_crea' => 0, 'valor' => 151, 'codigo' => '249', 'nombre' => 'ABUSO DE CONFIANZA'),
            array('usuario_crea' => 0, 'valor' => 152, 'codigo' => '250', 'nombre' => 'ABUSO DE CONFIANZA CALIFICADO'),
            array('usuario_crea' => 0, 'valor' => 153, 'codigo' => '250 A', 'nombre' => 'CORRUPCIÓN PRIVADA'),
            array('usuario_crea' => 0, 'valor' => 154, 'codigo' => '250 B', 'nombre' => 'ADMINISTRACIÓN DESLEAL'),
            array('usuario_crea' => 0, 'valor' => 155, 'codigo' => '251', 'nombre' => 'ABUSO DE CONDICIONES DE INFERIORIDAD'),
            array('usuario_crea' => 0, 'valor' => 156, 'codigo' => '252', 'nombre' => 'APROVECHAMIENTO DE ERROR AJENO O CASO FORTUITO'),
            array('usuario_crea' => 0, 'valor' => 157, 'codigo' => '253', 'nombre' => 'ALZAMIENTO DE BIENES'),
            array('usuario_crea' => 0, 'valor' => 158, 'codigo' => '254', 'nombre' => 'SUSTRACCION DE BIEN PROPIO'),
            array('usuario_crea' => 0, 'valor' => 159, 'codigo' => '255', 'nombre' => 'DISPOSICION DE BIEN PROPIO GRAVADO CON PRENDA'),
            array('usuario_crea' => 0, 'valor' => 160, 'codigo' => '256', 'nombre' => 'DEFRAUDACION DE FLUIDOS'),
            array('usuario_crea' => 0, 'valor' => 161, 'codigo' => '257', 'nombre' => 'DE LA PRESTACIÓN, ACCESO O USO ILEGALES DE LOS SERVICIOS DE TELECOMUNICACIONES.'),
            array('usuario_crea' => 0, 'valor' => 162, 'codigo' => '258', 'nombre' => 'UTILIZACION INDEBIDA DE INFORMACION PRIVILEGIADA'),
            array('usuario_crea' => 0, 'valor' => 163, 'codigo' => '259', 'nombre' => 'MALVERSACION Y DILAPIDACION DE BIENES'),
            array('usuario_crea' => 0, 'valor' => 164, 'codigo' => '260', 'nombre' => 'GESTION INDEBIDA DE RECURSOS SOCIALES'),
            array('usuario_crea' => 0, 'valor' => 165, 'codigo' => '261', 'nombre' => 'USURPACIÓN DE INMUEBLES'),
            array('usuario_crea' => 0, 'valor' => 166, 'codigo' => '262', 'nombre' => 'USURPACION DE AGUAS'),
            array('usuario_crea' => 0, 'valor' => 167, 'codigo' => '263', 'nombre' => 'NVASION DE TIERRAS O EDIFICACIONE'),
            array('usuario_crea' => 0, 'valor' => 168, 'codigo' => '264', 'nombre' => 'PERTURBACION DE LA POSESION SOBRE INMUEBLE'),
            array('usuario_crea' => 0, 'valor' => 169, 'codigo' => '265', 'nombre' => 'DAÑO EN BIEN AJENO.'),
            array('usuario_crea' => 0, 'valor' => 170, 'codigo' => '269.1', 'nombre' => 'DELITOS CONTRA EL PATRIMONIO CULTURAL SUMERGIDO.'),
            array('usuario_crea' => 0, 'valor' => 171, 'codigo' => '269 A', 'nombre' => 'ACCESO ABUSIVO A UN SISTEMA INFORMÁTICO.'),
            array('usuario_crea' => 0, 'valor' => 172, 'codigo' => '269 B', 'nombre' => 'OBSTACULIZACIÓN ILEGÍTIMA DE SISTEMA INFORMÁTICO O RED DE TELECOMUNICACIÓN. '),
            array('usuario_crea' => 0, 'valor' => 173, 'codigo' => '269 C', 'nombre' => 'INTERCEPTACIÓN DE DATOS INFORMÁTICOS'),
            array('usuario_crea' => 0, 'valor' => 174, 'codigo' => '269 D', 'nombre' => 'DAÑO INFORMÁTICO'),
            array('usuario_crea' => 0, 'valor' => 175, 'codigo' => '269 E', 'nombre' => 'USO DE SOFTWARE MALICIOSO.'),
            array('usuario_crea' => 0, 'valor' => 176, 'codigo' => '269 F', 'nombre' => 'VIOLACIÓN DE DATOS PERSONALES. '),
            array('usuario_crea' => 0, 'valor' => 177, 'codigo' => '269 G', 'nombre' => 'UPLANTACIÓN DE SITIOS WEB PARA CAPTURAR DATOS PERSONALES'),
            array('usuario_crea' => 0, 'valor' => 178, 'codigo' => ' 269 I', 'nombre' => 'HURTO POR MEDIOS INFORMÁTICOS Y SEMEJANTES'),
            array('usuario_crea' => 0, 'valor' => 179, 'codigo' => '269 J', 'nombre' => 'TRANSFERENCIA NO CONSENTIDA DE ACTIVOS.'),
            array('usuario_crea' => 0, 'valor' => 180, 'codigo' => '270', 'nombre' => 'VIOLACION A LOS DERECHOS MORALES DE AUTOR'),
            array('usuario_crea' => 0, 'valor' => 181, 'codigo' => '271', 'nombre' => 'VIOLACIÓN A LOS DERECHOS PATRIMONIALES DE AUTOR Y DERECHOS CONEXOS.'),
            array('usuario_crea' => 0, 'valor' => 182, 'codigo' => '272', 'nombre' => 'VIOLACIÓN A LOS MECANISMOS DE PROTECCIÓN DE DERECHO DE AUTOR Y DERECHOS CONEXOS, Y OTRAS DEFRAUDACIONES'),
            array('usuario_crea' => 0, 'valor' => 183, 'codigo' => '273', 'nombre' => 'FALSIFICACION DE MONEDA NACIONAL O EXTRANJERA'),
            array('usuario_crea' => 0, 'valor' => 184, 'codigo' => '274', 'nombre' => 'TRAFICO DE MONEDA FALSIFICADA'),
            array('usuario_crea' => 0, 'valor' => 185, 'codigo' => '275', 'nombre' => 'TRAFICO, ELABORACION Y TENENCIA DE ELEMENTOS DESTINADOS A LA FALSIFICACION DE MONEDA.'),
            array('usuario_crea' => 0, 'valor' => 186, 'codigo' => '276', 'nombre' => 'EMISIONES ILEGALES'),
            array('usuario_crea' => 0, 'valor' => 187, 'codigo' => '277', 'nombre' => 'CIRCULACION ILEGAL DE MONEDAS'),
            array('usuario_crea' => 0, 'valor' => 188, 'codigo' => '278', 'nombre' => 'VALORES EQUIPARADOS A MONEDA'),
            array('usuario_crea' => 0, 'valor' => 189, 'codigo' => '279', 'nombre' => 'FALSIFICACION O USO FRAUDULENTO DE SELLO OFICIAL'),
            array('usuario_crea' => 0, 'valor' => 190, 'codigo' => '280', 'nombre' => 'FALSIFICACION DE EFECTO OFICIAL TIMBRADO'),
            array('usuario_crea' => 0, 'valor' => 191, 'codigo' => '281', 'nombre' => 'CIRCULACION Y USO DE EFECTO OFICIAL O SELLO FALSIFICADO'),
            array('usuario_crea' => 0, 'valor' => 192, 'codigo' => '282', 'nombre' => 'EMISION ILEGAL DE EFECTOS OFICIALES'),
            array('usuario_crea' => 0, 'valor' => 193, 'codigo' => '283', 'nombre' => 'SUPRESION DE SIGNO DE ANULACION DE EFECTO OFICIAL'),
            array('usuario_crea' => 0, 'valor' => 194, 'codigo' => '284', 'nombre' => 'USO Y CIRCULACION DE EFECTO OFICIAL ANULADO'),
            array('usuario_crea' => 0, 'valor' => 195, 'codigo' => '285', 'nombre' => 'FALSEDAD MARCARIA.'),
            array('usuario_crea' => 0, 'valor' => 196, 'codigo' => '286', 'nombre' => 'FALSEDAD IDEOLOGICA EN DOCUMENTO PUBLICO'),
            array('usuario_crea' => 0, 'valor' => 197, 'codigo' => '287', 'nombre' => 'FALSEDAD MATERIAL EN DOCUMENTO PUBLICO'),
            array('usuario_crea' => 0, 'valor' => 198, 'codigo' => '288', 'nombre' => 'OBTENCION DE DOCUMENTO PUBLICO FALSO.'),
            array('usuario_crea' => 0, 'valor' => 199, 'codigo' => '289', 'nombre' => 'FALSEDAD EN DOCUMENTO PRIVADO'),
            array('usuario_crea' => 0, 'valor' => 200, 'codigo' => '291', 'nombre' => 'USO DE DOCUMENTO FALSO.'),
            array('usuario_crea' => 0, 'valor' => 201, 'codigo' => '292', 'nombre' => 'DESTRUCCION, SUPRESION U OCULTAMIENTO DE DOCUMENTO PUBLICO'),
            array('usuario_crea' => 0, 'valor' => 202, 'codigo' => '293', 'nombre' => 'DESTRUCCION, SUPRESION Y OCULTAMIENTO DE DOCUMENTO PRIVADO'),
            array('usuario_crea' => 0, 'valor' => 203, 'codigo' => '294', 'nombre' => '294'),
            array('usuario_crea' => 0, 'valor' => 204, 'codigo' => '295', 'nombre' => 'FALSEDAD PARA OBTENER PRUEBA DE HECHO VERDADERO'),
            array('usuario_crea' => 0, 'valor' => 205, 'codigo' => '296', 'nombre' => 'FALSEDAD PERSONAL'),
            array('usuario_crea' => 0, 'valor' => 206, 'codigo' => '297', 'nombre' => 'ACAPARAMIENTO.'),
            array('usuario_crea' => 0, 'valor' => 207, 'codigo' => '298', 'nombre' => 'ESPECULACION'),
            array('usuario_crea' => 0, 'valor' => 208, 'codigo' => '299', 'nombre' => 'ALTERACION Y MODIFICACION DE CALIDAD, CANTIDAD, PESO O MEDIDA.'),
            array('usuario_crea' => 0, 'valor' => 209, 'codigo' => '300', 'nombre' => 'OFRECIMIENTO ENGAÑOSO DE PRODUCTOS Y SERVICIOS'),
            array('usuario_crea' => 0, 'valor' => 210, 'codigo' => '301', 'nombre' => 'AGIOTAJE'),
            array('usuario_crea' => 0, 'valor' => 211, 'codigo' => '302', 'nombre' => 'PANICO ECONOMICO'),
            array('usuario_crea' => 0, 'valor' => 212, 'codigo' => '303', 'nombre' => 'ILICITA EXPLOTACION COMERCIAL'),
            array('usuario_crea' => 0, 'valor' => 213, 'codigo' => '304', 'nombre' => 'DAÑO EN MATERIA PRIMA, PRODUCTO AGROPECUARIO O INDUSTRIAL'),
            array('usuario_crea' => 0, 'valor' => 214, 'codigo' => '305', 'nombre' => 'USURA'),
            array('usuario_crea' => 0, 'valor' => 215, 'codigo' => '306', 'nombre' => 'USURPACIÓN DE DERECHOS DE PROPIEDAD INDUSTRIAL Y DERECHOS DE OBTENTORES DE VARIEDADES VEGETALES'),
            array('usuario_crea' => 0, 'valor' => 216, 'codigo' => '307', 'nombre' => 'USO ILEGITIMO DE PATENTES'),
            array('usuario_crea' => 0, 'valor' => 217, 'codigo' => '308', 'nombre' => 'VIOLACION DE RESERVA INDUSTRIAL O COMERCIA'),
            array('usuario_crea' => 0, 'valor' => 218, 'codigo' => '309', 'nombre' => 'SUSTRACCION DE COSA PROPIA AL CUMPLIMIENTO DE DEBERES CONSTITUCIONALES O LEGALES'),
            array('usuario_crea' => 0, 'valor' => 219, 'codigo' => '310', 'nombre' => 'EXPORTACION O IMPORTACION FICTICIA'),
            array('usuario_crea' => 0, 'valor' => 220, 'codigo' => '311', 'nombre' => 'APLICACION FRAUDULENTA DE CREDITO OFICIALMENTE REGULADO'),
            array('usuario_crea' => 0, 'valor' => 221, 'codigo' => '312', 'nombre' => 'EJERCICIO ILÍCITO DE ACTIVIDAD MONOPOLÍSTICA DE ARBITRIO RENTÍSTICO'),
            array('usuario_crea' => 0, 'valor' => 222, 'codigo' => '313', 'nombre' => 'EVASION FISCAL'),
            array('usuario_crea' => 0, 'valor' => 223, 'codigo' => '314', 'nombre' => 'UTILIZACION INDEBIDA DE FONDOS CAPTADOS DEL PUBLICO.'),
            array('usuario_crea' => 0, 'valor' => 224, 'codigo' => '315', 'nombre' => 'OPERACIONES NO AUTORIZADAS CON ACCIONISTAS O ASOCIADOS'),
            array('usuario_crea' => 0, 'valor' => 225, 'codigo' => '316', 'nombre' => 'CAPTACION MASIVA Y HABITUAL DE DINEROS'),
            array('usuario_crea' => 0, 'valor' => 226, 'codigo' => '317', 'nombre' => 'MANIPULACION FRAUDULENTA DE ESPECIES INSCRITAS EN EL REGISTRO NACIONAL DE VALORES E INTERMEDIARIOS'),
            array('usuario_crea' => 0, 'valor' => 227, 'codigo' => '318', 'nombre' => 'URBANIZACION ILEGAL'),
            array('usuario_crea' => 0, 'valor' => 228, 'codigo' => '319', 'nombre' => 'CONTRABANDO.'),
            array('usuario_crea' => 0, 'valor' => 229, 'codigo' => '319.1', 'nombre' => 'CONTRABANDO DE HIDROCARBUROS Y SUS DERIVADOS'),
            array('usuario_crea' => 0, 'valor' => 230, 'codigo' => '320', 'nombre' => 'FAVORECIMIENTO Y FACILITACIÓN DEL CONTRABANDO'),
            array('usuario_crea' => 0, 'valor' => 231, 'codigo' => '320.1', 'nombre' => 'FAVORECIMIENTO DE CONTRABANDO DE HIDROCARBUROS O SUS DERIVADOS'),
            array('usuario_crea' => 0, 'valor' => 232, 'codigo' => '321', 'nombre' => 'FRAUDE ADUANERO'),
            array('usuario_crea' => 0, 'valor' => 233, 'codigo' => '322', 'nombre' => 'FAVORECIMIENTO POR SERVIDOR PUBLICO'),
            array('usuario_crea' => 0, 'valor' => 234, 'codigo' => '322.1', 'nombre' => 'FAVORECIMIENTO POR SERVIDOR PÚBLICO DE CONTRABANDO DE HIDROCARBUROS O SUS DERIVADOS'),
            array('usuario_crea' => 0, 'valor' => 235, 'codigo' => '323', 'nombre' => 'LAVADO DE ACTIVOS'),
            array('usuario_crea' => 0, 'valor' => 236, 'codigo' => '325', 'nombre' => 'OMISION DE CONTROL'),
            array('usuario_crea' => 0, 'valor' => 237, 'codigo' => '325 A', 'nombre' => 'OMISIÓN DE REPORTES SOBRE TRANSACCIONES EN EFECTIVO, MOVILIZACIÓN O ALMACENAMIENTO DE DINERO EN EFECTIVO'),
            array('usuario_crea' => 0, 'valor' => 238, 'codigo' => '325 B', 'nombre' => 'OMISIÓN DE CONTROL EN EL SECTOR DE LA SALUD'),
            array('usuario_crea' => 0, 'valor' => 239, 'codigo' => '326', 'nombre' => 'TESTAFERRATO'),
            array('usuario_crea' => 0, 'valor' => 240, 'codigo' => '327', 'nombre' => 'ENRIQUECIMIENTO ILICITO DE PARTICULARES. '),
            array('usuario_crea' => 0, 'valor' => 241, 'codigo' => '327 A', 'nombre' => 'APODERAMIENTO DE HIDROCARBUROS, SUS DERIVADOS, BIOCOMBUSTIBLES O MEZCLAS QUE LOS CONTENGAN'),
            array('usuario_crea' => 0, 'valor' => 242, 'codigo' => '327 B', 'nombre' => 'APODERAMIENTO O ALTERACIÓN DE SISTEMAS DE IDENTIFICACIÓN'),
            array('usuario_crea' => 0, 'valor' => 243, 'codigo' => '327 C', 'nombre' => 'RECEPTACIÓN'),
            array('usuario_crea' => 0, 'valor' => 244, 'codigo' => ' 327 D', 'nombre' => 'DESTINACIÓN ILEGAL DE COMBUSTIBLES.'),
            array('usuario_crea' => 0, 'valor' => 245, 'codigo' => '328', 'nombre' => 'ILICITO APROVECHAMIENTO DE LOS RECURSOS NATURALES RENOVABLES.'),
            array('usuario_crea' => 0, 'valor' => 246, 'codigo' => '329', 'nombre' => 'VIOLACIÓN DE FRONTERAS PARA LA EXPLOTACIÓN O APROVECHAMIENTO DE LOS RECURSOS NATURALES'),
            array('usuario_crea' => 0, 'valor' => 247, 'codigo' => '330', 'nombre' => 'MANEJO Y USO ILÍCITO DE ORGANISMOS, MICROORGANISMOS Y ELEMENTOS GENÉTICAMENTE MODIFICADOS'),
            array('usuario_crea' => 0, 'valor' => 248, 'codigo' => '330 A', 'nombre' => 'MANEJO ILÍCITO DE ESPECIES EXÓTICAS'),
            array('usuario_crea' => 0, 'valor' => 249, 'codigo' => '331', 'nombre' => 'DAÑOS EN LOS RECURSOS NATURALES.'),
            array('usuario_crea' => 0, 'valor' => 250, 'codigo' => '332', 'nombre' => 'CONTAMINACIÓN AMBIENTAL POR RESIDUOS SÓLIDOS PELIGROSOS'),
            array('usuario_crea' => 0, 'valor' => 251, 'codigo' => '332 A', 'nombre' => 'CONTAMINACIÓN AMBIENTAL POR RESIDUOS SÓLIDOS PELIGROSOS'),
            array('usuario_crea' => 0, 'valor' => 252, 'codigo' => '333', 'nombre' => 'CONTAMINACIÓN AMBIENTAL POR EXPLOTACIÓN DE YACIMIENTO MINERO O HIDROCARBURO. '),
            array('usuario_crea' => 0, 'valor' => 253, 'codigo' => '334', 'nombre' => 'EXPERIMENTACIÓN ILEGAL CON ESPECIES, AGENTES BIOLÓGICOS O BIOQUÍMICOS'),
            array('usuario_crea' => 0, 'valor' => 254, 'codigo' => '335', 'nombre' => 'ILÍCITA ACTIVIDAD DE PESCA'),
            array('usuario_crea' => 0, 'valor' => 255, 'codigo' => '336', 'nombre' => 'CAZA ILEGAL'),
            array('usuario_crea' => 0, 'valor' => 256, 'codigo' => '337', 'nombre' => 'INVASIÓN DE ÁREAS DE ESPECIAL IMPORTANCIA ECOLÓGICA.'),
            array('usuario_crea' => 0, 'valor' => 257, 'codigo' => '338', 'nombre' => 'EXPLOTACION ILICITA DE YACIMIENTO MINERO Y OTROS MATERIALES'),
            array('usuario_crea' => 0, 'valor' => 258, 'codigo' => '339', 'nombre' => '339'),
            array('usuario_crea' => 0, 'valor' => 259, 'codigo' => '339 A', 'nombre' => 'DELITOS CONTRA LA VIDA, LA INTEGRIDAD FÍSICA Y EMOCIONAL DE LOS ANIMALES'),
            array('usuario_crea' => 0, 'valor' => 260, 'codigo' => '340', 'nombre' => 'CONCIERTO PARA DELINQUIR'),
            array('usuario_crea' => 0, 'valor' => 261, 'codigo' => '341', 'nombre' => 'ENTRENAMIENTO PARA ACTIVIDADES ILICITAS'),
            array('usuario_crea' => 0, 'valor' => 262, 'codigo' => '342', 'nombre' => '342'),
            array('usuario_crea' => 0, 'valor' => 263, 'codigo' => '343', 'nombre' => 'TERRORISMO'),
            array('usuario_crea' => 0, 'valor' => 264, 'codigo' => '344', 'nombre' => '344'),
            array('usuario_crea' => 0, 'valor' => 265, 'codigo' => '345', 'nombre' => 'FINANCIACIÓN DEL TERRORISMO Y DE GRUPOS DE DELINCUENCIA ORGANIZADA Y ADMINISTRACIÓN DE RECURSOS RELACIONADOS CON ACTIVIDADES TERRORISTAS Y DE LA DELINCUENCIA ORGANIZADA'),
            array('usuario_crea' => 0, 'valor' => 266, 'codigo' => '346', 'nombre' => 'UTILIZACION ILEGAL DE UNIFORMES E INSIGNIAS.'),
            array('usuario_crea' => 0, 'valor' => 267, 'codigo' => '347', 'nombre' => 'AMENAZAS'),
            array('usuario_crea' => 0, 'valor' => 268, 'codigo' => '348', 'nombre' => 'INSTIGACION A DELINQUIR'),
            array('usuario_crea' => 0, 'valor' => 269, 'codigo' => '349', 'nombre' => 'INCITACION A LA COMISION DE DELITOS MILITARES'),
            array('usuario_crea' => 0, 'valor' => 270, 'codigo' => '350', 'nombre' => 'INCENDIO'),
            array('usuario_crea' => 0, 'valor' => 271, 'codigo' => '351', 'nombre' => 'DAÑO EN OBRAS DE UTILIDAD SOCIAL'),
            array('usuario_crea' => 0, 'valor' => 272, 'codigo' => '352', 'nombre' => 'PROVOCACION DE INUNDACION O DERRUMBE'),
            array('usuario_crea' => 0, 'valor' => 273, 'codigo' => '353', 'nombre' => 'PERTURBACIÓN EN SERVICIO DE TRANSPORTE PÚBLICO, COLECTIVO U OFICIAL'),
            array('usuario_crea' => 0, 'valor' => 274, 'codigo' => '353 A', 'nombre' => 'OBSTRUCCIÓN A VÍAS PÚBLICAS QUE AFECTEN EL ORDEN PÚBLICO'),
            array('usuario_crea' => 0, 'valor' => 275, 'codigo' => '354', 'nombre' => 'SINIESTRO O DAÑO DE NAVE'),
            array('usuario_crea' => 0, 'valor' => 276, 'codigo' => '355', 'nombre' => 'PANICO.'),
            array('usuario_crea' => 0, 'valor' => 277, 'codigo' => '356', 'nombre' => 'DISPARO DE ARMA DE FUEGO CONTRA VEHICULO'),
            array('usuario_crea' => 0, 'valor' => 278, 'codigo' => '356 A', 'nombre' => 'DISPARO ARMA DE FUEGO'),
            array('usuario_crea' => 0, 'valor' => 279, 'codigo' => '357', 'nombre' => 'DAÑO EN OBRAS O ELEMENTOS DE LOS SERVICIOS DE COMUNICACIONES, ENERGIA Y COMBUSTIBLES'),
            array('usuario_crea' => 0, 'valor' => 280, 'codigo' => '358', 'nombre' => 'TENENCIA, FABRICACIÓN Y TRÁFICO DE SUSTANCIAS U OBJETOS PELIGROSOS'),
            array('usuario_crea' => 0, 'valor' => 281, 'codigo' => '359', 'nombre' => 'EMPLEO O LANZAMIENTO DE SUSTANCIAS U OBJETOS PELIGROSOS'),
            array('usuario_crea' => 0, 'valor' => 282, 'codigo' => '360', 'nombre' => '360'),
            array('usuario_crea' => 0, 'valor' => 283, 'codigo' => '361', 'nombre' => 'INTRODUCCION DE RESIDUOS NUCLEARES Y DE DESECHOS TOXICO'),
            array('usuario_crea' => 0, 'valor' => 284, 'codigo' => '362', 'nombre' => 'PERTURBACION DE INSTALACION NUCLEAR O RADIACTIVA'),
            array('usuario_crea' => 0, 'valor' => 285, 'codigo' => '363', 'nombre' => 'TRAFICO, TRANSPORTE Y POSESION DE MATERIALES RADIACTIVOS O SUSTANCIAS NUCLEARES'),
            array('usuario_crea' => 0, 'valor' => 286, 'codigo' => '364', 'nombre' => 'OBSTRUCCION DE OBRAS DE DEFENSA O DE ASISTENCIA'),
            array('usuario_crea' => 0, 'valor' => 287, 'codigo' => '365', 'nombre' => 'FABRICACIÓN, TRÁFICO, PORTE O TENENCIA DE ARMAS DE FUEGO, ACCESORIOS, PARTES O MUNICIONES. '),
            array('usuario_crea' => 0, 'valor' => 288, 'codigo' => '366', 'nombre' => 'FABRICACIÓN, TRÁFICO Y PORTE DE ARMAS, MUNICIONES DE USO RESTRINGIDO, DE USO PRIVATIVO DE LAS FUERZAS ARMADAS O EXPLOSIVOS'),
            array('usuario_crea' => 0, 'valor' => 289, 'codigo' => '367', 'nombre' => 'FABRICACION, IMPORTACION, TRAFICO, POSESION Y USO DE ARMAS QUIMICAS, BIOLOGICAS Y NUCLEARES.'),
            array('usuario_crea' => 0, 'valor' => 290, 'codigo' => '367 A', 'nombre' => 'EMPLEO, PRODUCCIÓN, COMERCIALIZACIÓN Y ALMACENAMIENTO DE MINAS ANTIPERSONAL'),
            array('usuario_crea' => 0, 'valor' => 291, 'codigo' => '367 B', 'nombre' => 'AYUDA E INDUCCIÓN AL EMPLEO, PRODUCCIÓN Y TRANSFERENCIA DE MINAS ANTIPERSONAL'),
            array('usuario_crea' => 0, 'valor' => 292, 'codigo' => '368', 'nombre' => 'VIOLACION DE MEDIDAS SANITARIAS'),
            array('usuario_crea' => 0, 'valor' => 293, 'codigo' => '369', 'nombre' => 'PROPAGACION DE EPIDEMIA'),
            array('usuario_crea' => 0, 'valor' => 294, 'codigo' => '370', 'nombre' => 'PROPAGACION DEL VIRUS DE INMUNODEFICIENCIA HUMANA O DE LA HEPATITIS B'),
            array('usuario_crea' => 0, 'valor' => 295, 'codigo' => '371', 'nombre' => 'CONTAMINACION DE AGUAS'),
            array('usuario_crea' => 0, 'valor' => 296, 'codigo' => '372', 'nombre' => 'CORRUPCION DE ALIMENTOS, PRODUCTOS MEDICOS O MATERIAL PROFILACTICO'),
            array('usuario_crea' => 0, 'valor' => 297, 'codigo' => '373', 'nombre' => 'IMITACION O SIMULACION DE ALIMENTOS, PRODUCTOS O SUSTANCIAS.'),
            array('usuario_crea' => 0, 'valor' => 298, 'codigo' => '374', 'nombre' => 'FABRICACION Y COMERCIALIZACION DE SUSTANCIAS NOCIVAS PARA LA SALUD'),
            array('usuario_crea' => 0, 'valor' => 299, 'codigo' => '374 A', 'nombre' => 'ENAJENACIÓN ILEGAL DE MEDICAMENTOS'),
            array('usuario_crea' => 0, 'valor' => 300, 'codigo' => '375', 'nombre' => 'CONSERVACION O FINANCIACION DE PLANTACIONES'),
            array('usuario_crea' => 0, 'valor' => 301, 'codigo' => '376', 'nombre' => 'TRAFICO, FABRICACION O PORTE DE ESTUPEFACIENTES'),
            array('usuario_crea' => 0, 'valor' => 302, 'codigo' => '377', 'nombre' => 'DESTINACION ILICITA DE MUEBLES O INMUEBLES'),
            array('usuario_crea' => 0, 'valor' => 303, 'codigo' => '377 A', 'nombre' => 'USO, CONSTRUCCIÓN, COMERCIALIZACIÓN Y/O TENENCIA DE SEMISUMERGIBLES O SUMERGIBLES'),
            array('usuario_crea' => 0, 'valor' => 304, 'codigo' => '378', 'nombre' => 'ESTIMULO AL USO ILICITO'),
            array('usuario_crea' => 0, 'valor' => 305, 'codigo' => '379', 'nombre' => 'SUMINISTRO O FORMULACION ILEGA'),
            array('usuario_crea' => 0, 'valor' => 306, 'codigo' => '380', 'nombre' => 'SUMINISTRO O FORMULACION ILEGA'),
            array('usuario_crea' => 0, 'valor' => 307, 'codigo' => '381', 'nombre' => 'SUMINISTRO A MENOR'),
            array('usuario_crea' => 0, 'valor' => 308, 'codigo' => '382', 'nombre' => 'TRÁFICO DE SUSTANCIAS PARA EL PROCESAMIENTO DE NARCÓTICOS.'),
            array('usuario_crea' => 0, 'valor' => 309, 'codigo' => '383', 'nombre' => 'PORTE DE SUSTANCIAS. '),
            array('usuario_crea' => 0, 'valor' => 310, 'codigo' => '385', 'nombre' => 'EXISTENCIA, CONSTRUCCION Y UTILIZACION ILEGAL DE PISTAS DE ATERRIZAJE'),
            array('usuario_crea' => 0, 'valor' => 311, 'codigo' => '386', 'nombre' => 'PERTURBACION DE CERTAMEN DEMOCRATICO'),
            array('usuario_crea' => 0, 'valor' => 312, 'codigo' => '387', 'nombre' => 'CONSTREÑIMIENTO AL SUFRAGANTE'),
            array('usuario_crea' => 0, 'valor' => 313, 'codigo' => '388', 'nombre' => 'FRAUDE AL SUFRAGANTE'),
            array('usuario_crea' => 0, 'valor' => 314, 'codigo' => '389', 'nombre' => 'FRAUDE EN INSCRIPCION DE CEDULAS'),
            array('usuario_crea' => 0, 'valor' => 315, 'codigo' => '389 A', 'nombre' => 'ELECCIÓN ILÍCITA DE CANDIDATOS'),
            array('usuario_crea' => 0, 'valor' => 316, 'codigo' => '390', 'nombre' => 'CORRUPCION DE SUFRAGANTE. '),
            array('usuario_crea' => 0, 'valor' => 317, 'codigo' => '390 A', 'nombre' => 'TRÁFICO DE VOTOS'),
            array('usuario_crea' => 0, 'valor' => 318, 'codigo' => '391', 'nombre' => 'VOTO FRAUDULENTO'),
            array('usuario_crea' => 0, 'valor' => 319, 'codigo' => '392', 'nombre' => 'FAVORECIMIENTO DE VOTO FRAUDULENTO'),
            array('usuario_crea' => 0, 'valor' => 320, 'codigo' => '393', 'nombre' => 'MORA EN LA ENTREGA DE DOCUMENTOS RELACIONADOS CON UNA VOTACION.'),
            array('usuario_crea' => 0, 'valor' => 321, 'codigo' => '394', 'nombre' => 'ALTERACION DE RESULTADOS ELECTORALES'),
            array('usuario_crea' => 0, 'valor' => 322, 'codigo' => '395', 'nombre' => 'OCULTAMIENTO, RETENCION Y POSESION ILICITA DE CEDULA'),
            array('usuario_crea' => 0, 'valor' => 323, 'codigo' => '396', 'nombre' => 'DENEGACION DE INSCRIPCION'),
            array('usuario_crea' => 0, 'valor' => 324, 'codigo' => '396 A', 'nombre' => 'FINANCIACIÓN DE CAMPAÑAS ELECTORALES CON FUENTES PROHIBIDAS.'),
            array('usuario_crea' => 0, 'valor' => 325, 'codigo' => '396 B', 'nombre' => 'VIOLACIÓN DE LOS TOPES O LÍMITES DE GASTOS EN LAS CAMPAÑAS ELECTORALES'),
            array('usuario_crea' => 0, 'valor' => 326, 'codigo' => '396 C', 'nombre' => 'OMISIÓN DE INFORMACIÓN DEL APORTANTE'),
            array('usuario_crea' => 0, 'valor' => 327, 'codigo' => '397', 'nombre' => 'PECULADO POR APROPIACION. '),
            array('usuario_crea' => 0, 'valor' => 328, 'codigo' => '398', 'nombre' => 'PECULADO POR USO'),
            array('usuario_crea' => 0, 'valor' => 329, 'codigo' => '399', 'nombre' => 'PECULADO POR APLICACION OFICIAL DIFERENTE'),
            array('usuario_crea' => 0, 'valor' => 330, 'codigo' => '399 A', 'nombre' => 'PECULADO POR APLICACIÓN OFICIAL DIFERENTE FRENTE A RECURSOS DE LA SEGURIDAD SOCIAL'),
            array('usuario_crea' => 0, 'valor' => 331, 'codigo' => '400', 'nombre' => 'PECULADO CULPOSO'),
            array('usuario_crea' => 0, 'valor' => 332, 'codigo' => '400 A', 'nombre' => 'PECULADO CULPOSO FRENTE A RECURSOS DE LA SEGURIDAD SOCIAL INTEGRAL'),
            array('usuario_crea' => 0, 'valor' => 333, 'codigo' => '402', 'nombre' => 'OMISION DEL AGENTE RETENEDOR O RECAUDADOR'),
            array('usuario_crea' => 0, 'valor' => 334, 'codigo' => '403', 'nombre' => 'DESTINO DE RECURSOS DEL TESORO PARA EL ESTIMULO O BENEFICIO INDEBIDO DE EXPLOTADORES Y COMERCIANTES DE METALES PRECIOSOS.'),
            array('usuario_crea' => 0, 'valor' => 335, 'codigo' => '403 A', 'nombre' => 'FRAUDE DE SUBVENCIONES.'),
            array('usuario_crea' => 0, 'valor' => 336, 'codigo' => '404', 'nombre' => 'CONCUSION'),
            array('usuario_crea' => 0, 'valor' => 337, 'codigo' => '405', 'nombre' => 'COHECHO PROPIO'),
            array('usuario_crea' => 0, 'valor' => 338, 'codigo' => '406', 'nombre' => 'COHECHO IMPROPIO'),
            array('usuario_crea' => 0, 'valor' => 339, 'codigo' => '407', 'nombre' => 'COHECHO POR DAR U OFRECER. '),
            array('usuario_crea' => 0, 'valor' => 340, 'codigo' => '408', 'nombre' => 'VIOLACION DEL REGIMEN LEGAL O CONSTITUCIONAL DE INHABILIDADES E INCOMPATIBILIDADES'),
            array('usuario_crea' => 0, 'valor' => 341, 'codigo' => '409', 'nombre' => 'INTERES INDEBIDO EN LA CELEBRACION DE CONTRATOS'),
            array('usuario_crea' => 0, 'valor' => 342, 'codigo' => '410', 'nombre' => 'CONTRATO SIN CUMPLIMIENTO DE REQUISITOS LEGALES'),
            array('usuario_crea' => 0, 'valor' => 343, 'codigo' => '410 A', 'nombre' => 'ACUERDOS RESTRICTIVOS DE LA COMPETENCIA.'),
            array('usuario_crea' => 0, 'valor' => 344, 'codigo' => '411', 'nombre' => 'TRAFICO DE INFLUENCIAS DE SERVIDOR PUBLICO'),
            array('usuario_crea' => 0, 'valor' => 345, 'codigo' => '411 A', 'nombre' => 'TRÁFICO DE INFLUENCIAS DE PARTICULAR'),
            array('usuario_crea' => 0, 'valor' => 346, 'codigo' => '412', 'nombre' => 'ENRIQUECIMIENTO ILICITO'),
            array('usuario_crea' => 0, 'valor' => 347, 'codigo' => '413', 'nombre' => 'PREVARICATO POR ACCION'),
            array('usuario_crea' => 0, 'valor' => 348, 'codigo' => '414', 'nombre' => 'PREVARICATO POR OMISION'),
            array('usuario_crea' => 0, 'valor' => 349, 'codigo' => '416', 'nombre' => 'ABUSO DE AUTORIDAD POR ACTO ARBITRARIO E INJUSTO'),
            array('usuario_crea' => 0, 'valor' => 350, 'codigo' => '417', 'nombre' => 'ABUSO DE AUTORIDAD POR OMISION DE DENUNCIA.'),
            array('usuario_crea' => 0, 'valor' => 351, 'codigo' => '418', 'nombre' => 'REVELACION DE SECRETO'),
            array('usuario_crea' => 0, 'valor' => 352, 'codigo' => '419', 'nombre' => 'UTILIZACION DE ASUNTO SOMETIDO A SECRETO O RESERVA.'),
            array('usuario_crea' => 0, 'valor' => 353, 'codigo' => '420', 'nombre' => 'UTILIZACION INDEBIDA DE INFORMACION OFICIAL PRIVILEGIADA'),
            array('usuario_crea' => 0, 'valor' => 354, 'codigo' => '421', 'nombre' => 'ASESORAMIENTO Y OTRAS ACTUACIONES ILEGALES'),
            array('usuario_crea' => 0, 'valor' => 355, 'codigo' => '422', 'nombre' => 'INTERVENCION EN POLITICA'),
            array('usuario_crea' => 0, 'valor' => 356, 'codigo' => '423', 'nombre' => 'EMPLEO ILEGAL DE LA FUERZA PUBLICA'),
            array('usuario_crea' => 0, 'valor' => 357, 'codigo' => '424', 'nombre' => 'OMISION DE APOYO'),
            array('usuario_crea' => 0, 'valor' => 358, 'codigo' => '425', 'nombre' => 'USURPACION DE FUNCIONES PUBLICAS'),
            array('usuario_crea' => 0, 'valor' => 359, 'codigo' => '426', 'nombre' => 'SIMULACION DE INVESTIDURA O CARGO'),
            array('usuario_crea' => 0, 'valor' => 360, 'codigo' => '427', 'nombre' => 'USURPACIÓN Y ABUSO DE FUNCIONES PÚBLICAS CON FINES TERRORISTAS'),
            array('usuario_crea' => 0, 'valor' => 361, 'codigo' => '428', 'nombre' => 'ABUSO DE FUNCION PUBLICA.'),
            array('usuario_crea' => 0, 'valor' => 362, 'codigo' => '429', 'nombre' => 'VIOLENCIA CONTRA SERVIDOR PÚBLICO'),
            array('usuario_crea' => 0, 'valor' => 363, 'codigo' => '430', 'nombre' => 'PERTURBACION DE ACTOS OFICIALES.'),
            array('usuario_crea' => 0, 'valor' => 364, 'codigo' => '431', 'nombre' => 'UTILIZACIÓN INDEBIDA DE INFORMACIÓN OBTENIDA EN EL EJERCICIO DE FUNCIÓN PÚBLICA'),
            array('usuario_crea' => 0, 'valor' => 365, 'codigo' => '432', 'nombre' => 'UTILIZACION INDEBIDA DE INFLUENCIAS DERIVADAS DEL EJERCICIO DE FUNCION PUBLICA'),
            array('usuario_crea' => 0, 'valor' => 366, 'codigo' => '433', 'nombre' => 'SOBORNO TRANSNACIONAL'),
            array('usuario_crea' => 0, 'valor' => 367, 'codigo' => '434', 'nombre' => 'ASOCIACION PARA LA COMISION DE UN DELITO CONTRA LA ADMINISTRACION PUBLICA'),
            array('usuario_crea' => 0, 'valor' => 368, 'codigo' => '434 A', 'nombre' => 'OMISIÓN DE ACTIVOS O INCLUSIÓN DE PASIVOS INEXISTENTES'),
            array('usuario_crea' => 0, 'valor' => 369, 'codigo' => '435', 'nombre' => 'FALSA DENUNCIA'),
            array('usuario_crea' => 0, 'valor' => 370, 'codigo' => '436', 'nombre' => 'FALSA DENUNCIA CONTRA PERSONA DETERMINADA'),
            array('usuario_crea' => 0, 'valor' => 371, 'codigo' => '437', 'nombre' => 'FALSA AUTOACUSACION'),
            array('usuario_crea' => 0, 'valor' => 372, 'codigo' => '441', 'nombre' => 'OMISION DE DENUNCIA DE PARTICULAR.'),
            array('usuario_crea' => 0, 'valor' => 373, 'codigo' => '442', 'nombre' => 'FALSO TESTIMONIO'),
            array('usuario_crea' => 0, 'valor' => 374, 'codigo' => '444', 'nombre' => 'SOBORNO'),
            array('usuario_crea' => 0, 'valor' => 375, 'codigo' => '444 A', 'nombre' => 'SOBORNO EN LA ACTUACIÓN PENAL'),
            array('usuario_crea' => 0, 'valor' => 376, 'codigo' => '445', 'nombre' => 'INFIDELIDAD A LOS DEBERES PROFESIONALES.'),
            array('usuario_crea' => 0, 'valor' => 377, 'codigo' => '446', 'nombre' => 'FAVORECIMIENTO'),
            array('usuario_crea' => 0, 'valor' => 378, 'codigo' => '447', 'nombre' => 'RECEPTACIÓN'),
            array('usuario_crea' => 0, 'valor' => 379, 'codigo' => '448', 'nombre' => 'FUGA DE PRESOS.'),
            array('usuario_crea' => 0, 'valor' => 380, 'codigo' => '449', 'nombre' => 'FAVORECIMIENTO DE LA FUGA'),
            array('usuario_crea' => 0, 'valor' => 381, 'codigo' => '450', 'nombre' => 'MODALIDAD CULPOSA'),
            array('usuario_crea' => 0, 'valor' => 382, 'codigo' => '452', 'nombre' => 'EXIMIENTE DE RESPONSABILIDAD PENAL'),
            array('usuario_crea' => 0, 'valor' => 383, 'codigo' => '453', 'nombre' => 'FRAUDE PROCESAL'),
            array('usuario_crea' => 0, 'valor' => 384, 'codigo' => '454', 'nombre' => 'FRAUDE A RESOLUCIÓN JUDICIAL O ADMINISTRATIVA DE POLICÍA'),
            array('usuario_crea' => 0, 'valor' => 385, 'codigo' => '454 A', 'nombre' => 'AMENAZAS A TESTIGO'),
            array('usuario_crea' => 0, 'valor' => 386, 'codigo' => '454 B', 'nombre' => 'OCULTAMIENTO, ALTERACIÓN O DESTRUCCIÓN DE ELEMENTO MATERIAL PROBATORIO. '),
            array('usuario_crea' => 0, 'valor' => 387, 'codigo' => '454 C', 'nombre' => 'IMPEDIMENTO O PERTURBACIÓN DE LA CELEBRACIÓN DE AUDIENCIAS PÚBLICAS.'),
            array('usuario_crea' => 0, 'valor' => 388, 'codigo' => '455', 'nombre' => 'MENOSCABO DE LA INTEGRIDAD NACIONAL'),
            array('usuario_crea' => 0, 'valor' => 389, 'codigo' => '456', 'nombre' => 'HOSTILIDAD MILITAR'),
            array('usuario_crea' => 0, 'valor' => 390, 'codigo' => '457', 'nombre' => 'TRAICION DIPLOMATICA'),
            array('usuario_crea' => 0, 'valor' => 391, 'codigo' => '458', 'nombre' => 'INSTIGACION A LA GUERRA'),
            array('usuario_crea' => 0, 'valor' => 392, 'codigo' => '459', 'nombre' => 'ATENTADOS CONTRA HITOS FRONTERIZOS'),
            array('usuario_crea' => 0, 'valor' => 393, 'codigo' => '460', 'nombre' => 'ACTOS CONTRARIOS A LA DEFENSA DE LA NACION'),
            array('usuario_crea' => 0, 'valor' => 394, 'codigo' => '462', 'nombre' => 'ACEPTACION INDEBIDA DE HONORES'),
            array('usuario_crea' => 0, 'valor' => 395, 'codigo' => '463', 'nombre' => 'ESPIONAJE'),
            array('usuario_crea' => 0, 'valor' => 396, 'codigo' => '464', 'nombre' => 'VIOLACION DE TREGUA O ARMISTICIO'),
            array('usuario_crea' => 0, 'valor' => 397, 'codigo' => '465', 'nombre' => 'VIOLACION DE INMUNIDAD DIPLOMATICA'),
            array('usuario_crea' => 0, 'valor' => 398, 'codigo' => '466', 'nombre' => 'OFENSA A DIPLOMATICOS'),
            array('usuario_crea' => 0, 'valor' => 399, 'codigo' => '467', 'nombre' => 'REBELION'),
            array('usuario_crea' => 0, 'valor' => 400, 'codigo' => '468', 'nombre' => 'SEDICION.'),
            array('usuario_crea' => 0, 'valor' => 401, 'codigo' => '469', 'nombre' => 'ASONADA'),
            array('usuario_crea' => 0, 'valor' => 402, 'codigo' => '471', 'nombre' => 'CONSPIRACION'),
            array('usuario_crea' => 0, 'valor' => 403, 'codigo' => '472', 'nombre' => 'SEDUCCION, USURPACION Y RETENCION ILEGAL DE MANDO'),
        ];
        for ($i=0; $i < count($datos); $i++) { 
            Para_Delito::create($datos[$i]);
        }
    }
}
