<?php
date_default_timezone_set('America/Bogota');

use App\Models\Para_DespachoJ;
use Illuminate\Database\Seeder;

class SeedParaDespachoJ extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            array('usuario_crea' => 0, 'valor' => 1, 'nombre' => '1 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE DE CIUDAD BOLÍVAR'),
            array('usuario_crea' => 0, 'valor' => 2, 'nombre' => '2 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE DE CIUDAD BOLÍVAR'),
            array('usuario_crea' => 0, 'valor' => 3, 'nombre' => '1 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE DE KENNEDY'),
            array('usuario_crea' => 0, 'valor' => 4, 'nombre' => '2 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE DE KENNEDY'),
            array('usuario_crea' => 0, 'valor' => 5, 'nombre' => '3 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 6, 'nombre' => '4 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 7, 'nombre' => '5 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 8, 'nombre' => '6 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 9, 'nombre' => '7 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 10, 'nombre' => '8 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 11, 'nombre' => '9 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 12, 'nombre' => '10 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 13, 'nombre' => '11 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 14, 'nombre' => '12 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 15, 'nombre' => '13 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 16, 'nombre' => '14 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 17, 'nombre' => '15 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 18, 'nombre' => '16 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 19, 'nombre' => '17 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 20, 'nombre' => '18 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 21, 'nombre' => '19 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 22, 'nombre' => '20 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 23, 'nombre' => '21 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 24, 'nombre' => '22 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 25, 'nombre' => '23 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 26, 'nombre' => '24 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 27, 'nombre' => '27 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 28, 'nombre' => '28 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 29, 'nombre' => '29 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 30, 'nombre' => '30 CIVIL MUNICIPAL DE DESCONGESTIÓN - COMPETENCIA MULTIPLE'),
            array('usuario_crea' => 0, 'valor' => 31, 'nombre' => '1 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 32, 'nombre' => '2 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 33, 'nombre' => '3 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 34, 'nombre' => '4 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 35, 'nombre' => '5 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 36, 'nombre' => '6 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 37, 'nombre' => '7 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 38, 'nombre' => '8 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 39, 'nombre' => '9 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 40, 'nombre' => '10 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 41, 'nombre' => '11 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 42, 'nombre' => '12 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 43, 'nombre' => '13 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 44, 'nombre' => '14 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 45, 'nombre' => '15 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 46, 'nombre' => '16 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 47, 'nombre' => '17 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 48, 'nombre' => '18 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 49, 'nombre' => '19 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 50, 'nombre' => '20 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 51, 'nombre' => '21 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 52, 'nombre' => '22 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 53, 'nombre' => '23 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 54, 'nombre' => '24 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 55, 'nombre' => '25 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 56, 'nombre' => '26 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 57, 'nombre' => '27 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 58, 'nombre' => '28 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 59, 'nombre' => '29 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 60, 'nombre' => '30 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 61, 'nombre' => '31 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 62, 'nombre' => '32 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 63, 'nombre' => '33 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 64, 'nombre' => '34 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 65, 'nombre' => '35 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 66, 'nombre' => '36 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 67, 'nombre' => '37 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 68, 'nombre' => '38 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 69, 'nombre' => '39 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 70, 'nombre' => '40 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 71, 'nombre' => '41 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 72, 'nombre' => '42 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 73, 'nombre' => '43 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 74, 'nombre' => '44 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 75, 'nombre' => '45 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 76, 'nombre' => '46 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 77, 'nombre' => '47 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 78, 'nombre' => '48 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 79, 'nombre' => '49 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 80, 'nombre' => '50 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 81, 'nombre' => '51 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 82, 'nombre' => '52 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 83, 'nombre' => '53 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 84, 'nombre' => '54 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 85, 'nombre' => '55 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 86, 'nombre' => '56 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 87, 'nombre' => '57 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 88, 'nombre' => '58 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 89, 'nombre' => '59 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 90, 'nombre' => '60 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 91, 'nombre' => '61 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 92, 'nombre' => '62 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 93, 'nombre' => '63 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 94, 'nombre' => '64 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 95, 'nombre' => '65 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 96, 'nombre' => '66 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 97, 'nombre' => '67 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 98, 'nombre' => '68 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 99, 'nombre' => '69 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 100, 'nombre' => '70 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 101, 'nombre' => '71 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 102, 'nombre' => '72 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 103, 'nombre' => '73 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 104, 'nombre' => '74 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 105, 'nombre' => '75 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 106, 'nombre' => '76 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 107, 'nombre' => '77 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 108, 'nombre' => '78 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 109, 'nombre' => '79 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 110, 'nombre' => '80 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 111, 'nombre' => '81 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 112, 'nombre' => '82 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 113, 'nombre' => '83 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 114, 'nombre' => '84 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 115, 'nombre' => '85 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 116, 'nombre' => '86 CIVIL MUNICIPAL'),
            array('usuario_crea' => 0, 'valor' => 117, 'nombre' => '40 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 118, 'nombre' => '41 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 119, 'nombre' => '42 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 120, 'nombre' => '43 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 121, 'nombre' => '44 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 122, 'nombre' => '45 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 123, 'nombre' => '46 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 124, 'nombre' => '47 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 125, 'nombre' => '48 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 126, 'nombre' => '49 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 127, 'nombre' => '50 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 128, 'nombre' => '51 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 129, 'nombre' => '52 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 130, 'nombre' => '53 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 131, 'nombre' => '54 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 132, 'nombre' => '55 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 133, 'nombre' => '56 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 134, 'nombre' => '57 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 135, 'nombre' => '58 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 136, 'nombre' => '59 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 137, 'nombre' => '60 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 138, 'nombre' => '61 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 139, 'nombre' => '62 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 140, 'nombre' => '63 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 141, 'nombre' => '64 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 142, 'nombre' => '65 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 143, 'nombre' => '66 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 144, 'nombre' => '67 PEQUEÑAS CAUSAS'),
            array('usuario_crea' => 0, 'valor' => 145, 'nombre' => '68 PEQUEÑAS CAUSAS'),            
        ];
        for ($i=0; $i < count($datos); $i++) { 
            Para_DespachoJ::create($datos[$i]);
        }
    }
}
