<?php
date_default_timezone_set('America/Bogota');

use App\Models\Para_Clase_Diligencia;
use Illuminate\Database\Seeder;

class SeedParaClaseDiligencia extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            //========================== Clase de diligencia Penales1 ==========================
                array('usuario_crea' => 0, 'valor' => 1, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SOLICITUD DE MEDIDAS PARA PROTECCIÓN A VÍCTIMAS Y TESTIGOS'),
                array('usuario_crea' => 0, 'valor' => 2, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'CONTROL DE LEGALIDAD DE REGISTRO Y ALLANAMIENTO E INCAUTACIÓN DE E.M.P Y E.F'),
                array('usuario_crea' => 0, 'valor' => 3, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SOLICITUD DE CAPTURA Y/O CONTROL DE LEGALIDAD A LA CAPTURA'),
                array('usuario_crea' => 0, 'valor' => 4, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'BUSQUEDA SELECTIVA EN BASE DE DATOS, INTERCEPTACIONES TELEFÓNICAS Y SIMILARES'),
                array('usuario_crea' => 0, 'valor' => 5, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'PETICIÓN DE MEDIDAS CAUTELARES REALES'),
                array('usuario_crea' => 0, 'valor' => 6, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'CONTROL DE LEGALIDAD SOBRE APLICACIÓN DE PRINCIPIO DE OPORTUNIDAD'),
                array('usuario_crea' => 0, 'valor' => 7, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'FORMULACIÓN DE IMPUTACIÓN'),
                array('usuario_crea' => 0, 'valor' => 8, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SOLICITUD DE MEDIDAS CAUTELARES EN FAVOR DE VICTIMAS MENORES DE EDAD O INCAPAZ M.P.'),
                array('usuario_crea' => 0, 'valor' => 9, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SOLICITUD DE SUSTITUCIÓN DE DETENCIÓN DOMICILIARIA M.P.'),
                array('usuario_crea' => 0, 'valor' => 10, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'DECLARATORIA DE CONTUMACIA / PERSONA AUSENTE'),
                array('usuario_crea' => 0, 'valor' => 11, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SUSPENSIÓN DEL PODER DISPOSITIVO'),
                array('usuario_crea' => 0, 'valor' => 12, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SOLICITUD, IMPOSICIÓN, SUSTITUCIÓN O REVOCATORIA DE MEDIDA DE ASEGURAMIENTO'),
                array('usuario_crea' => 0, 'valor' => 13, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SOLICITUD DE PRECLUSIÓN'),
                array('usuario_crea' => 0, 'valor' => 14, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'LIBERTAD POR VENCIMIENTO DE TERMINOS'),
                array('usuario_crea' => 0, 'valor' => 15, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'VERIFICACIÓN DE PREACUERDO'),
                array('usuario_crea' => 0, 'valor' => 16, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'FORMULACIÓN DE ACUSACIÓN'),
                array('usuario_crea' => 0, 'valor' => 17, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'PREPARATORIA DEL JUICIO'),
                array('usuario_crea' => 0, 'valor' => 18, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'SESIÓN DE JUICIO ORAL / ALEGATOS DE CONCLUSIÓN'),
                array('usuario_crea' => 0, 'valor' => 19, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'INDIVIDUALIZACIÓN DE PENA / SENTENCIA'),
                array('usuario_crea' => 0, 'valor' => 20, 'id_tipo_mp' => 1, 'id_actuacion' => 1, 'nombre' => 'INCIDENTE DE REPARACIÓN INTEGRAL'),
                array('usuario_crea' => 0, 'valor' => 21, 'id_tipo_mp' => 6, 'id_actuacion' => 2, 'nombre' => 'SUSTENTACIÓN DE RECURSO DE REPOSICIÓN'),
                array('usuario_crea' => 0, 'valor' => 22, 'id_tipo_mp' => 6, 'id_actuacion' => 2, 'nombre' => 'SUSTENTACIÓN DE RECURSO DE APELACIÓN'),
                array('usuario_crea' => 0, 'valor' => 23, 'id_tipo_mp' => 6, 'id_actuacion' => 2, 'nombre' => 'SUSTENTACIÓN DE RECURSO DE QUEJA'),
                array('usuario_crea' => 0, 'valor' => 24, 'id_tipo_mp' => 6, 'id_actuacion' => 2, 'nombre' => 'INTERVENCIÓN COMO NO RECURRENTE'),
                array('usuario_crea' => 0, 'valor' => 25, 'id_tipo_mp' => 6, 'id_actuacion' => 3, 'nombre' => 'DE NULIDAD'),
                array('usuario_crea' => 0, 'valor' => 26, 'id_tipo_mp' => 6, 'id_actuacion' => 3, 'nombre' => 'DE DESARCHIVO ANTE FISCALIA'),
                array('usuario_crea' => 0, 'valor' => 27, 'id_tipo_mp' => 1, 'id_actuacion' => 3, 'nombre' => 'DE DESARCHIVO ANTE JUZGADOS DE CONTROL DE GARANTIAS'),
                array('usuario_crea' => 0, 'valor' => 28, 'id_tipo_mp' => 1, 'id_actuacion' => 4, 'nombre' => 'DE ACTOS DE INVESTIGACIÓN'),
                array('usuario_crea' => 0, 'valor' => 29, 'id_tipo_mp' => 1, 'id_actuacion' => 4, 'nombre' => 'PROCESALES ANTE FISCALÍA'),
                array('usuario_crea' => 0, 'valor' => 30, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'DILIGENCIA DE ALLANAMIENTO Y REGISTRO'),
                array('usuario_crea' => 0, 'valor' => 31, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'DILIGENCIA DE RECONOCIMIENTO FOTOGRÁFICO'),
                array('usuario_crea' => 0, 'valor' => 32, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'DILIGENCIA DE RECONOCIMIENTO EN FILA DE PERSONAS'),
                array('usuario_crea' => 0, 'valor' => 33, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'DESTRUCCIÓN DEL OBJETO MATERIAL DEL DELITO'),
                array('usuario_crea' => 0, 'valor' => 34, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'ENTREVISTA O DECLARACIÓN JURADA'),
                array('usuario_crea' => 0, 'valor' => 35, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'INTERRROGATORIO A INDICIADO'),
                array('usuario_crea' => 0, 'valor' => 36, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'COMISIONES ANTE FUNCIONARIO JUDICIAL'),
                array('usuario_crea' => 0, 'valor' => 37, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'ACCIÓNES DE TUTELA INTERPUESTAS'),
                array('usuario_crea' => 0, 'valor' => 38, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'DERECHO DE PETICIÓN TRAMITADO'),
                array('usuario_crea' => 0, 'valor' => 39, 'id_tipo_mp' => 1, 'id_actuacion' => 5, 'nombre' => 'OTRAS ACTUACIONES E INTERVENCIONES'),
                array('usuario_crea' => 0, 'valor' => 40, 'id_tipo_mp' => 1, 'id_actuacion' => 6, 'nombre' => 'AUDIENCIA CONCENTRADA (ART. 542. LEY 1826/17)'),
                array('usuario_crea' => 0, 'valor' => 41, 'id_tipo_mp' => 1, 'id_actuacion' => 6, 'nombre' => 'AUDIENCIA DE JUICIO ORAL'),
                array('usuario_crea' => 0, 'valor' => 42, 'id_tipo_mp' => 1, 'id_actuacion' => 6, 'nombre' => 'INDIVIDUALIZACIÓN DE PENA (ART. 447 C.P.P.)'),
                array('usuario_crea' => 0, 'valor' => 43, 'id_tipo_mp' => 1, 'id_actuacion' => 7, 'nombre' => 'SUSTENTACIÓN DE RECURSO DE REPOSICIÓN'),
                array('usuario_crea' => 0, 'valor' => 44, 'id_tipo_mp' => 1, 'id_actuacion' => 7, 'nombre' => 'SUSTENTACIÓN DE RECURSO DE APELACIÓN'),
                array('usuario_crea' => 0, 'valor' => 45, 'id_tipo_mp' => 1, 'id_actuacion' => 7, 'nombre' => 'SUSTENTACIÓN DE RECURSO DE QUEJA'),
                array('usuario_crea' => 0, 'valor' => 46, 'id_tipo_mp' => 1, 'id_actuacion' => 7, 'nombre' => 'INTERVENCIÓN COMO NO RECURRENTE'),
                array('usuario_crea' => 0, 'valor' => 47, 'id_tipo_mp' => 1, 'id_actuacion' => 8, 'nombre' => 'ALEGATOS PRECALIFICATORIOS'),
                array('usuario_crea' => 0, 'valor' => 48, 'id_tipo_mp' => 1, 'id_actuacion' => 8, 'nombre' => 'ALEGATOS DE CONCLUSIÓN'),
                array('usuario_crea' => 0, 'valor' => 49, 'id_tipo_mp' => 1, 'id_actuacion' => 9, 'nombre' => 'AUDIENCIA Y/O SESIÓN PÚBLICA JUZGAMIENTO'),
                array('usuario_crea' => 0, 'valor' => 50, 'id_tipo_mp' => 1, 'id_actuacion' => 9, 'nombre' => 'AUDIENCIA Y/O SESIÓN PÚBLICA PREPARATORIA'),
                array('usuario_crea' => 0, 'valor' => 51, 'id_tipo_mp' => 6, 'id_actuacion' => 10, 'nombre' => 'SUSTENTACIÓN RECURSO REPOSICIÓN M.P.'),
                array('usuario_crea' => 0, 'valor' => 52, 'id_tipo_mp' => 6, 'id_actuacion' => 10, 'nombre' => 'SUSTENTACIÓN RECURSO APELACIÓN M.P.'),
                array('usuario_crea' => 0, 'valor' => 53, 'id_tipo_mp' => 6, 'id_actuacion' => 10, 'nombre' => 'INTERVENCIÓN RECURSO DE QUEJA M.P.'),
                array('usuario_crea' => 0, 'valor' => 54, 'id_tipo_mp' => 6, 'id_actuacion' => 10, 'nombre' => 'INTERVENCIÓN COMO NO RECURRENTE EN APELACIÓN / REPOSICIÓN'),
                array('usuario_crea' => 0, 'valor' => 55, 'id_tipo_mp' => 1, 'id_actuacion' => 11, 'nombre' => 'ALLANAMIENTOS Y REGISTROS'),
                array('usuario_crea' => 0, 'valor' => 56, 'id_tipo_mp' => 1, 'id_actuacion' => 11, 'nombre' => 'RECONOCIMIENTO FOTOGRÁFICO Y DE FILA DE PERSONAS'),
                array('usuario_crea' => 0, 'valor' => 57, 'id_tipo_mp' => 1, 'id_actuacion' => 11, 'nombre' => 'DESTRUCCIÓN DE EVIDENCIAS FÍSICAS'),
                array('usuario_crea' => 0, 'valor' => 58, 'id_tipo_mp' => 1, 'id_actuacion' => 11, 'nombre' => 'INDAGATORIA - FORMULACIÓN DE CARGOS'),
                array('usuario_crea' => 0, 'valor' => 59, 'id_tipo_mp' => 1, 'id_actuacion' => 11, 'nombre' => 'DECLARACIONES'),
                array('usuario_crea' => 0, 'valor' => 60, 'id_tipo_mp' => 1, 'id_actuacion' => 11, 'nombre' => 'INSPECCIÓN JUDICIAL'),
                array('usuario_crea' => 0, 'valor' => 61, 'id_tipo_mp' => 6, 'id_actuacion' => 12, 'nombre' => 'DE NULIDAD'),
                array('usuario_crea' => 0, 'valor' => 62, 'id_tipo_mp' => 6, 'id_actuacion' => 12, 'nombre' => 'DE PRUEBAS'),
                array('usuario_crea' => 0, 'valor' => 63, 'id_tipo_mp' => 1, 'id_actuacion' => 12, 'nombre' => 'SOBRE LIBERTAD Y BIENES'),
                array('usuario_crea' => 0, 'valor' => 64, 'id_tipo_mp' => 1, 'id_actuacion' => 12, 'nombre' => 'IMPEDIMENTO Y/O RECUSACIÓN'),
                array('usuario_crea' => 0, 'valor' => 65, 'id_tipo_mp' => 1, 'id_actuacion' => 12, 'nombre' => 'MEDIDA DE PROTECCIÓN'),
                array('usuario_crea' => 0, 'valor' => 66, 'id_tipo_mp' => 1, 'id_actuacion' => 12, 'nombre' => 'DERECHOS DE PETICIÓN TRAMITADOS'),
                array('usuario_crea' => 0, 'valor' => 67, 'id_tipo_mp' => 1, 'id_actuacion' => 12, 'nombre' => 'OTRAS SOLICITUDES O ACTUACIONES ANTE FUNCIONARIO JUDICIAL'),
            //========================== Clase de diligencia Penales2 ==========================
                array('usuario_crea' => 0, 'valor' => 68, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'DE CONCILIACIÓN'),
                array('usuario_crea' => 0, 'valor' => 69, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE PRÁCTICA DE PRUEBA ANTICIPADA'),
                array('usuario_crea' => 0, 'valor' => 70, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'PETICIÓN DE MEDIDAS CAUTELARES REALES'),
                array('usuario_crea' => 0, 'valor' => 71, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE MEDIDAS PARA PROTECCIÓN A VÍCTIMAS Y TESTIGOS'),
                array('usuario_crea' => 0, 'valor' => 72, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'CONTROL DE LEGALIDAD SOBRE APLICACIÓN DE PRINCIPIO DE OPORTUNIDAD'),
                array('usuario_crea' => 0, 'valor' => 73, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'CONTROL DE LEGALIDAD DE REGISTRO'),
                array('usuario_crea' => 0, 'valor' => 74, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'ALLANAMIENTO E INCAUTACIÓN DE E.M.P. Y E.F.'),
                array('usuario_crea' => 0, 'valor' => 75, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE CAPTURA'),
                array('usuario_crea' => 0, 'valor' => 76, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'CONTROL DE LEGALIDAD A LA CAPTURA'),
                array('usuario_crea' => 0, 'valor' => 77, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'FORMULACIÓN DE IMPUTACIÓN'),
                array('usuario_crea' => 0, 'valor' => 78, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'IMPOSICIÓN, SUSTITUCIÓN O REVOCATORIA DE MEDIDA DE ASEGURAMIENTO'),
                array('usuario_crea' => 0, 'valor' => 79, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'BUSQUEDA SELECTIVA EN BASE DE DATOS, INTERCEPTACIONES TELEFÓNICAS Y SIMILARES'),
                array('usuario_crea' => 0, 'valor' => 80, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE MEDIDAS CAUTELARES EN FAVOR DE VICTIMAS MENORES DE EDAD O INCAPAZ M.P.'),
                array('usuario_crea' => 0, 'valor' => 81, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE SUSTITUCIÓN DE DETENCIÓN DOMICILIARIA M.P.'),
                array('usuario_crea' => 0, 'valor' => 82, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE REVOCATORIA DE DETENCIÓN DOMICILIARIA'),
                array('usuario_crea' => 0, 'valor' => 83, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE REVOCATORIA POR INCUMPLIMIENTO DE OBLIGACIONES EN MEDIDA DE ASEGURAMIENTO NO PRIVATIVA DE LA LIBERTAD'),
                array('usuario_crea' => 0, 'valor' => 84, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'SOLICITUD DE PRECLUSIÓN'),
                array('usuario_crea' => 0, 'valor' => 85, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'DECLARATORIA DE CONTUMACIA'),
                array('usuario_crea' => 0, 'valor' => 86, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'DECLARACIÓN DE PERSONA AUSENTE'),
                array('usuario_crea' => 0, 'valor' => 87, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'AUTORIZACIÓN MEDICO LEGAL'),
                array('usuario_crea' => 0, 'valor' => 88, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'AUTORIZACIÓN DE REGISTRO CORPORAL'),
                array('usuario_crea' => 0, 'valor' => 89, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'LEGALIZACIÓN DE INCAUTACIÓN'),
                array('usuario_crea' => 0, 'valor' => 90, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'ENTREGA DE VEHICULO'),
                array('usuario_crea' => 0, 'valor' => 91, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'LEGALIZACIÓN DE SUSPENCIÓN DEL PODER DISPOSITIVO'),
                array('usuario_crea' => 0, 'valor' => 92, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'LIBERTAD POR VENCIMIENTO DE TERMINOS'),
                array('usuario_crea' => 0, 'valor' => 93, 'id_tipo_mp' => 2, 'id_actuacion' => 13, 'nombre' => 'CONTROL PREVIO Y POSTERIOR A ORDENES DE POLICIA JUDICIAL'),
                array('usuario_crea' => 0, 'valor' => 94, 'id_tipo_mp' => 2, 'id_actuacion' => 3, 'nombre' => 'RESTABLECIMIENTO DEL DERECHO'),
                array('usuario_crea' => 0, 'valor' => 95, 'id_tipo_mp' => 2, 'id_actuacion' => 3, 'nombre' => 'IMPULSO PROCESAL'),
                array('usuario_crea' => 0, 'valor' => 96, 'id_tipo_mp' => 2, 'id_actuacion' => 3, 'nombre' => 'COMPULSA DE COPIAS DISCIPLINARIAS'),
                array('usuario_crea' => 0, 'valor' => 97, 'id_tipo_mp' => 2, 'id_actuacion' => 3, 'nombre' => 'COMPULSA DE COPIAS PENALES'),
                array('usuario_crea' => 0, 'valor' => 98, 'id_tipo_mp' => 2, 'id_actuacion' => 3, 'nombre' => 'MEDIDAS DE PROTECCIÓN'),
                array('usuario_crea' => 0, 'valor' => 99, 'id_tipo_mp' => 2, 'id_actuacion' => 3, 'nombre' => 'COMISO EN AUDIENCIA'),
                array('usuario_crea' => 0, 'valor' => 100, 'id_tipo_mp' => 2, 'id_actuacion' => 3, 'nombre' => 'DE DESARCHIVO ANTE JUZGADO'),
                array('usuario_crea' => 0, 'valor' => 101, 'id_tipo_mp' => 2, 'id_actuacion' => 14, 'nombre' => 'DERECHOS DE PETICIÓN TRAMITADOS Y RESPONDIDOS'),
                array('usuario_crea' => 0, 'valor' => 102, 'id_tipo_mp' => 2, 'id_actuacion' => 14, 'nombre' => 'INFORME SOBRE CONDICIONES DE RECLUSIÓN'),
                array('usuario_crea' => 0, 'valor' => 103, 'id_tipo_mp' => 2, 'id_actuacion' => 14, 'nombre' => 'RESPUESTA ACCIÓNES DE TUTELA INTERPUESTAS'),
                array('usuario_crea' => 0, 'valor' => 104, 'id_tipo_mp' => 2, 'id_actuacion' => 14, 'nombre' => 'PRESENTACIÓN DE QUERELLAS POR M.P.'),
                array('usuario_crea' => 0, 'valor' => 105, 'id_tipo_mp' => 2, 'id_actuacion' => 9, 'nombre' => 'DE CONCILIACIÓN'),
                array('usuario_crea' => 0, 'valor' => 106, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'DILIGENCIA DE ALLANAMIENTO Y REGISTRO'),
                array('usuario_crea' => 0, 'valor' => 107, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'DILIGENCIA DE RECONOCIMIENTO FOTOGRÁFICO'),
                array('usuario_crea' => 0, 'valor' => 108, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'DILIGENCIA DE RECONOCIMIENTO EN FILA DE PERSONAS'),
                array('usuario_crea' => 0, 'valor' => 109, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'DESTRUCCIÓN DE EVIDENCIAS'),
                array('usuario_crea' => 0, 'valor' => 110, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'ENTREGA VIGILADA'),
                array('usuario_crea' => 0, 'valor' => 111, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'ASISTENCIA A PESAJE'),
                array('usuario_crea' => 0, 'valor' => 112, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'EXHUMACIONES'),
                array('usuario_crea' => 0, 'valor' => 113, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'ENTREVISTA O DECLARACIÓN JURADA'),
                array('usuario_crea' => 0, 'valor' => 114, 'id_tipo_mp' => 2, 'id_actuacion' => 15, 'nombre' => 'INTERROGATORIO A INDICIADO'),
                array('usuario_crea' => 0, 'valor' => 115, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'ALLANAMIENTOS Y REGISTROS'),
                array('usuario_crea' => 0, 'valor' => 116, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'RECONOCIMIENTO FOTOGRÁFICO'),
                array('usuario_crea' => 0, 'valor' => 117, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'RECONOCIMIENTO DE FILA DE PERSONAS'),
                array('usuario_crea' => 0, 'valor' => 118, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'DESTRUCCIÓN DE EVIDENCIAS'),
                array('usuario_crea' => 0, 'valor' => 119, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'INDAGATORIA'),
                array('usuario_crea' => 0, 'valor' => 120, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'VERSIÓN LIBRE'),
                array('usuario_crea' => 0, 'valor' => 121, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'INSPECCIÓN JUDICIAL'),
                array('usuario_crea' => 0, 'valor' => 122, 'id_tipo_mp' => 2, 'id_actuacion' => 16, 'nombre' => 'DECLARACIONES'),
                array('usuario_crea' => 0, 'valor' => 123, 'id_tipo_mp' => 2, 'id_actuacion' => 12, 'nombre' => 'SOBRE MEDIDAS CAUTELARES REALES'),
                array('usuario_crea' => 0, 'valor' => 124, 'id_tipo_mp' => 2, 'id_actuacion' => 12, 'nombre' => 'SOBRE LIBERTAD'),
                array('usuario_crea' => 0, 'valor' => 125, 'id_tipo_mp' => 2, 'id_actuacion' => 12, 'nombre' => 'CAMBIO DE RADICACIÓN'),
                array('usuario_crea' => 0, 'valor' => 126, 'id_tipo_mp' => 2, 'id_actuacion' => 12, 'nombre' => 'IMPEDIMENTO'),
                array('usuario_crea' => 0, 'valor' => 127, 'id_tipo_mp' => 2, 'id_actuacion' => 12, 'nombre' => 'RECUSACIÓN'),
                array('usuario_crea' => 0, 'valor' => 128, 'id_tipo_mp' => 2, 'id_actuacion' => 17, 'nombre' => 'ALEGATOS PRERESOLUTORIOS DE SITUACIÓN JURIDICA'),
                array('usuario_crea' => 0, 'valor' => 129, 'id_tipo_mp' => 2, 'id_actuacion' => 17, 'nombre' => 'DERECHOS DE PETICIÓN TRAMITADOS Y RESPONDIDOS'),
                array('usuario_crea' => 0, 'valor' => 130, 'id_tipo_mp' => 2, 'id_actuacion' => 17, 'nombre' => 'ALEGATOS PRECALIFICATORIOS'),
                array('usuario_crea' => 0, 'valor' => 131, 'id_tipo_mp' => 2, 'id_actuacion' => 17, 'nombre' => 'RESPUESTA ACCIÓNES DE TUTELA INTERPUESTAS'),
                array('usuario_crea' => 0, 'valor' => 132, 'id_tipo_mp' => 2, 'id_actuacion' => 17, 'nombre' => 'SOLICITUD DE CONTROL DE LEGALIDAD DE MEDIDA DE ASEGURAMIENTO'),
                array('usuario_crea' => 0, 'valor' => 133, 'id_tipo_mp' => 2, 'id_actuacion' => 17, 'nombre' => 'OTRAS SOLICITUDES O ACTUACIONES ANTE FUNCIONARIO JUDICIAL'),
            //========================== Clase de diligencia Movilidad ==========================
                array('usuario_crea' => 0, 'valor' => 134, 'id_tipo_mp' => 3, 'id_actuacion' => 18, 'nombre' => 'ACOMPAÑAMIENTO AUDIENCIA DE IMPUGNACIÓN DE COMPARENDO'),
                array('usuario_crea' => 0, 'valor' => 135, 'id_tipo_mp' => 3, 'id_actuacion' => 19, 'nombre' => 'INTERROGATORIO'),
                array('usuario_crea' => 0, 'valor' => 136, 'id_tipo_mp' => 3, 'id_actuacion' => 19, 'nombre' => 'SOLICITUD DE PRUEBAS'),
                array('usuario_crea' => 0, 'valor' => 137, 'id_tipo_mp' => 3, 'id_actuacion' => 19, 'nombre' => 'SOLICITUD COMPULSA DE COPIAS DISCIPLINARIAS'),
            //========================== Clase de diligencia Juzgados ==========================
                array('usuario_crea' => 0, 'valor' => 138, 'id_tipo_mp' => 4, 'id_actuacion' => 20, 'nombre' => 'IMPULSO PROCESAL'),
                array('usuario_crea' => 0, 'valor' => 139, 'id_tipo_mp' => 4, 'id_actuacion' => 20, 'nombre' => 'SOLICITUD COMPULSA DE COPIAS DISCIPLINARIAS'),
                array('usuario_crea' => 0, 'valor' => 140, 'id_tipo_mp' => 4, 'id_actuacion' => 20, 'nombre' => 'SOLICITUD DE NULIDAD'),
                array('usuario_crea' => 0, 'valor' => 141, 'id_tipo_mp' => 4, 'id_actuacion' => 20, 'nombre' => 'RECURSO'),
                array('usuario_crea' => 0, 'valor' => 142, 'id_tipo_mp' => 4, 'id_actuacion' => 20, 'nombre' => 'SOLICITUD DE PRUEBAS'),
                array('usuario_crea' => 0, 'valor' => 143, 'id_tipo_mp' => 4, 'id_actuacion' => 21, 'nombre' => 'INTERVENCIÓN DE MP COMO GARANTE DE DERECHOS FUNDAMENTALES'),
            //========================== Clase de diligencia Segunda ==========================
                array('usuario_crea' => 0, 'valor' => 144, 'id_tipo_mp' => 5, 'id_actuacion' => 22, 'nombre' => 'VERIFICACIÓN CUMPLIMIENTO ORDEN DE POLICÍA'),
                array('usuario_crea' => 0, 'valor' => 145, 'id_tipo_mp' => 5, 'id_actuacion' => 22, 'nombre' => 'REQUERIMIENTO ALCALDE LOCAL O INSPECTOR'),
                array('usuario_crea' => 0, 'valor' => 146, 'id_tipo_mp' => 5, 'id_actuacion' => 22, 'nombre' => 'SOLICITUD COMPULSA DE COPIAS DISCIPLINARIOS'),
        ];
        for ($i=0; $i < count($datos); $i++) { 
            Para_Clase_Diligencia::create($datos[$i]);
        }
    }
}
